using System.Text.Json;

namespace Okf.Cli.Tests;

/// <summary>
/// The shapes the CLI renders: the machine-readable JSON of PRD CLI-11/CLI-15 and the
/// human report beside it. The JSON is a contract other tooling reads, so its indentation,
/// its trailing newline and every one of its keys are asserted; the text report is asserted
/// where a branch in it decides what a reader is told.
/// </summary>
public class ReportRenderingTests
{
    /// <summary>
    /// <c>okf lint --json</c> writes an indented array — the form a diff and a human both
    /// read — terminated by a newline, with every key present on every element and in the
    /// order the writer emits them, so a consumer can read each one unconditionally.
    /// </summary>
    [Fact]
    public void LintJsonIsIndentedAndCarriesEveryKey()
    {
        using var tree = new TempTree();
        var bundle = tree.CopyFixture("warnings-only", "bundle");

        var run = Cli.RunIn(tree.Root, tree.Root, "lint", bundle, "--json");

        Assert.EndsWith("\n", run.Output, StringComparison.Ordinal);
        Assert.Contains("\n  {\n    \"id\":", run.Output, StringComparison.Ordinal);

        using var parsed = JsonDocument.Parse(run.Output);
        var elements = parsed.RootElement.EnumerateArray().ToList();
        Assert.NotEmpty(elements);
        foreach (var element in elements)
        {
            string[] keys =
                ["id", "rule", "severity", "path", "absolutePath", "line", "bundle", "message"];
            Assert.Equal(keys, element.EnumerateObject().Select(property => property.Name).ToArray());
            Assert.True(Path.IsPathRooted(element.GetProperty("absolutePath").GetString()));
            Assert.False(Path.IsPathRooted(element.GetProperty("path").GetString()));
            Assert.NotEqual(string.Empty, element.GetProperty("bundle").GetString());
        }
    }

    /// <summary>
    /// <c>okf index --json</c> reports each index's status by name. The three a normal run
    /// produces — a first pass, a second pass, and a hand-written file being replaced — are
    /// asserted through the same vault at three points in its life (AD-13/AD-14).
    /// </summary>
    [Fact]
    public void IndexJsonReportsEachIndexesStatusByName()
    {
        using var tree = new TempTree();
        tree.CopyFixture("conformant", Path.Combine("okf", "bundles", "clean"));
        tree.Write(
            Path.Combine("okf", "bundles", "clean", "index.md"),
            "# Hand written\n\nNot generated by okf.\n");

        var replacing = Cli.RunIn(tree.Root, tree.Root, "index", "--json");
        var unchanged = Cli.RunIn(tree.Root, tree.Root, "index", "--json");

        Assert.Contains("\"status\": \"foreign\"", replacing.Output, StringComparison.Ordinal);
        Assert.Contains("\"status\": \"unchanged\"", unchanged.Output, StringComparison.Ordinal);
        Assert.EndsWith("\n", unchanged.Output, StringComparison.Ordinal);

        using var parsed = JsonDocument.Parse(unchanged.Output);
        foreach (var element in parsed.RootElement.EnumerateArray())
        {
            string[] keys = ["path", "absolutePath", "bundle", "status", "drift", "bundleRoot", "entries"];
            Assert.Equal(keys, element.EnumerateObject().Select(property => property.Name).ToArray());
            Assert.True(Path.IsPathRooted(element.GetProperty("absolutePath").GetString()));
            Assert.True(Path.IsPathRooted(element.GetProperty("bundle").GetString()));
        }
    }

    /// <summary>
    /// A vault whose generated indexes have been removed reports them as created on the
    /// next run and as unchanged on the one after, so the summary counts distinguish a
    /// first pass from a no-op (PRD CLI-10).
    /// </summary>
    [Fact]
    public void IndexReportsCreatedThenUnchanged()
    {
        using var tree = new TempTree();
        tree.CopyFixture("conformant", Path.Combine("okf", "bundles", "clean"));
        foreach (var index in Directory.EnumerateFiles(
                     Path.Combine(tree.Root, "okf"), "index.md", SearchOption.AllDirectories))
        {
            File.Delete(index);
        }

        var first = Cli.RunIn(tree.Root, tree.Root, "index", "--json");
        var second = Cli.RunIn(tree.Root, tree.Root, "index");

        Assert.Contains("\"status\": \"created\"", first.Output, StringComparison.Ordinal);
        Assert.Contains("0 created, 0 updated, ", second.Summary, StringComparison.Ordinal);
    }

    /// <summary>
    /// <c>okf search --json</c> reports the match mode it used: <c>all</c> when every term
    /// matched something, <c>any</c> when the fallback widened the query (AD-28). The two
    /// values are what a caller keys on to know whether it is looking at an exact answer.
    /// </summary>
    [Theory]
    [InlineData("widget", "all")]
    [InlineData("widget nonexistentterm", "any")]
    public void SearchJsonReportsTheMatchMode(string query, string expected)
    {
        using var tree = new TempTree();
        WriteSearchableBundle(tree);

        var run = Cli.RunIn(tree.Root, tree.Root, "search", query, "--json");

        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);
        Assert.EndsWith("\n", run.Output, StringComparison.Ordinal);
        Assert.Contains("\n  {\n", run.Output, StringComparison.Ordinal);

        using var parsed = JsonDocument.Parse(run.Output);
        foreach (var element in parsed.RootElement.EnumerateArray())
        {
            Assert.Equal(expected, element.GetProperty("matchMode").GetString());
        }
    }

    /// <summary>
    /// <c>okf search</c>'s text report prints the matched excerpt under the result when
    /// there is one to print (AD-28's snippet), and the ranked line above it always.
    /// </summary>
    [Fact]
    public void SearchTextPrintsTheSnippetUnderTheResult()
    {
        using var tree = new TempTree();
        WriteSearchableBundle(tree);

        var run = Cli.RunIn(tree.Root, tree.Root, "search", "widgets", "--limit", "1");

        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);
        Assert.Matches(@"(?m)^1\. \d+\.\d{4}  \S+  Widget", run.Output);
        Assert.Matches(@"(?m)^    \S.*widget", run.Output);
    }

    /// <summary>
    /// A result whose match is in its frontmatter rather than its prose has no excerpt to
    /// show, and the report prints no line for it — an indented empty line under a result
    /// reads as a snippet that came back blank.
    /// </summary>
    [Fact]
    public void SearchTextOmitsTheSnippetLineWhenThereIsNoExcerpt()
    {
        using var tree = new TempTree();
        tree.Write(
            Path.Combine("okf", "bundles", "widgets", "bundle.yaml"),
            """
            okf_version: "0.2"
            name: widgets
            """);
        tree.Write(
            Path.Combine("okf", "bundles", "widgets", "concepts", "titled.md"),
            "---\nid: titled\ntype: concept\ntitle: Widget\n---\n");

        var run = Cli.RunIn(tree.Root, tree.Root, "search", "widget");

        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);
        Assert.Matches(@"(?m)^1\. ", run.Output);
        Assert.DoesNotMatch(@"(?m)^ +$", run.Output);
    }

    /// <summary>
    /// <c>okf registry --json</c> is indented and newline-terminated like every other JSON
    /// report, so `okf register` output can be committed and diffed (AD-51).
    /// </summary>
    [Fact]
    public void RegistryJsonIsIndentedAndNewlineTerminated()
    {
        using var tree = new TempTree();
        var vault = tree.CreateDirectory(Path.Combine("okf", "bundles", "clean"));

        var registered = Cli.RunIn(tree.Root, tree.Root, "register", Path.Combine(tree.Root, "okf"));
        var listed = Cli.RunIn(tree.Root, tree.Root, "registry", "--json");

        Assert.Equal(CliApplication.ExitSuccess, registered.ExitCode);
        Assert.Equal(CliApplication.ExitSuccess, listed.ExitCode);
        Assert.EndsWith("\n", listed.Output, StringComparison.Ordinal);
        Assert.Contains("\n  {\n", listed.Output, StringComparison.Ordinal);

        using var parsed = JsonDocument.Parse(listed.Output);
        Assert.Single(parsed.RootElement.EnumerateArray());
        Assert.NotNull(vault);
    }

    /// <summary>
    /// The registry's text summary counts the entries whose path is gone and points at the
    /// verb that removes them, in the singular or the plural as the count requires — and
    /// says neither when every path is present. Each row pins the tail from the closing
    /// quote of the registry path onward, so the no-missing row asserts that the sentence
    /// ends there rather than merely that the output contains a full stop somewhere.
    /// </summary>
    [Theory]
    [InlineData(0, "'.")]
    [InlineData(1, "'; 1 path missing — `okf registry prune` removes it.")]
    [InlineData(2, "'; 2 paths missing — `okf registry prune` removes them.")]
    public void RegistrySummaryCountsMissingPaths(int missing, string expected)
    {
        using var tree = new TempTree();
        for (var index = 0; index < 3; index++)
        {
            var vault = tree.CreateDirectory(Path.Combine($"vault{index}", "bundles", "b"));
            var run = Cli.RunIn(tree.Root, tree.Root, "register", Path.Combine(tree.Root, $"vault{index}"));
            Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);
            Assert.NotNull(vault);
        }

        for (var index = 0; index < missing; index++)
        {
            Directory.Delete(Path.Combine(tree.Root, $"vault{index}"), recursive: true);
        }

        var listed = Cli.RunIn(tree.Root, tree.Root, "registry");

        Assert.Equal(CliApplication.ExitSuccess, listed.ExitCode);
        Assert.Contains($"3 entries in '", listed.Output, StringComparison.Ordinal);
        Assert.Contains(expected, listed.Output, StringComparison.Ordinal);
    }

    /// <summary>
    /// The inbox's detail line prefixes <c>status: draft;</c> only for a concept that says
    /// it is a draft. Both halves matter: the prefix is what tells a reader the concept was
    /// never claimed to be finished, and its absence is what keeps a finished concept from
    /// looking unfinished.
    /// </summary>
    [Theory]
    [InlineData("status: draft", true)]
    [InlineData("generated:\n  by: tests\n  at: 2020-01-01T00:00:00Z", false)]
    public void InboxDetailMarksDraftsOnly(string frontmatter, bool draft)
    {
        using var tree = new TempTree();
        var bundle = tree.CreateDirectory(Path.Combine("vault", "bundles", "b"));
        tree.Write(
            Path.Combine("vault", "bundles", "b", "concept.md"),
            $"---\ntype: Concept\ntitle: Waiting\n{frontmatter}\n---\n\nBody.\n");

        var run = Cli.RunIn(tree.Root, tree.Root, "inbox", bundle);

        Assert.Contains("never verified", run.Output, StringComparison.Ordinal);
        Assert.Equal(draft, run.Output.Contains("status: draft; ", StringComparison.Ordinal));
    }

    /// <summary>
    /// A day count in the future reads as "in N days", not as a negative age: a
    /// <c>generated.at</c> stamp ahead of today is a clock problem, and reporting it as
    /// "-3 days ago" would hide that.
    /// </summary>
    [Fact]
    public void InboxRendersAFutureStampAsDaysAhead()
    {
        using var tree = new TempTree();
        var bundle = tree.CreateDirectory(Path.Combine("vault", "bundles", "b"));
        var ahead = DateTimeOffset.UtcNow.AddDays(3).ToString("yyyy-MM-dd'T'HH:mm:ss'Z'", null);
        tree.Write(
            Path.Combine("vault", "bundles", "b", "concept.md"),
            $"---\ntype: Concept\ntitle: Ahead\ngenerated:\n  by: tests\n  at: {ahead}\n---\n\nBody.\n");

        var run = Cli.RunIn(tree.Root, tree.Root, "inbox", bundle);

        Assert.Contains("(in 3 days)", run.Output, StringComparison.Ordinal);
    }

    private static void WriteSearchableBundle(TempTree tree)
    {
        tree.Write(
            Path.Combine("okf", "bundles", "widgets", "bundle.yaml"),
            """
            okf_version: "0.2"
            name: widgets
            """);
        tree.Write(
            Path.Combine("okf", "bundles", "widgets", "concepts", "widget-one.md"),
            """
            ---
            id: widget-one
            type: concept
            title: Widget one
            ---

            # Widget one

            A widget that widgets, among other widgets.
            """);
    }
}
