using System.Globalization;
using System.Text.Json;
using System.Text.RegularExpressions;
using Okf.Core;

namespace Okf.Cli.Tests.Candidates;

/// <summary>
/// The dogfood contract for <c>okf candidates</c> (work item #81): this repository's own bundle
/// carries a concept describing the command, written by this branch, and the command lists that
/// concept as an unverified candidate when pointed at its own vault.
/// </summary>
/// <remarks>
/// <para>
/// The feature's claim is that the tool reaches its own change rather than a fixture, and a
/// fixture cannot carry that claim. A scanner that skipped the directory the concept landed in
/// would pass every temp-tree test in <see cref="CandidatesCommandTests" /> while the acceptance
/// criterion went false, because nothing in those tests is a file this repository wrote in order
/// to ship the verb. So the assertions here run over <c>okf/</c> as committed, and the concept is
/// named by path: the run is only a self-run if the file it names is the file the change added.
/// </para>
/// <para>
/// Expected values come from the concept's own bytes and from the commands' own output, not from
/// literals typed beside the assertions they would agree with. The literals that do appear are
/// the exit codes, which are #71's contract rather than a fact about this bundle, and the reason
/// sentence, which #74's eligibility table fixes.
/// </para>
/// </remarks>
public class CandidateDogfoodTests
{
    /// <summary>
    /// The concept this change adds, vault-relative. Named once, because every assertion below is
    /// about that one file: a test that accepted "some concept about candidates" would still pass
    /// if the concept moved, renamed itself, or were replaced by a stub.
    /// </summary>
    private const string ConceptPath = "bundles/okf-net/toolset/capability-describes-itself.md";

    /// <summary>The same path as a candidate record reports it, bundle-relative (§2).</summary>
    private const string ConceptBundlePath = "toolset/capability-describes-itself.md";

    /// <summary>
    /// The self-run the acceptance criteria ask for: the new command against the repository's own
    /// vault lists this concept and exits 0.
    /// </summary>
    /// <remarks>
    /// Exit 0 is the half that is easy to lose. This vault holds no verification events anywhere,
    /// so every concept in it is a candidate; a run that went red on a full backlog would satisfy
    /// "lists this concept" while breaking the contract that makes the command usable as a scan
    /// step — an inventory reports its length as an answer, and only an unclassified concept moves
    /// the exit code (#71, AD-56).
    /// </remarks>
    [SkippableFact]
    public void TheCommandListsTheConceptThisBranchWroteAndExitsZero()
    {
        using var vault = TheVault();
        var run = CliHarness.RunIn(vault.Root, vault.Home, "candidates", vault.Path);

        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);

        // Matched as a row rather than as any occurrence: the path is what a caller opens, and a
        // run that named the file only in prose would not be a listing of it.
        string row = Assert.Single(
            run.OutputLines,
            line => line.Contains(vault.Displayed(ConceptPath), StringComparison.Ordinal));

        // The row carries the tier as derived and the type as written — both read off the file's
        // own frontmatter here rather than typed, so a row that stopped printing either one, or
        // printed a tier the file does not derive, goes red.
        Assert.Contains($"[{RowTrustTier(vault)}]", row, StringComparison.Ordinal);
        Assert.Contains($"({RowType(vault)})", row, StringComparison.Ordinal);

        // The line under the row is the library's sentence about the shape the file holds, and the
        // shape here is an absent key — which the frontmatter confirms independently of the run.
        Assert.DoesNotContain("verified", Frontmatter(vault), StringComparison.Ordinal);
        int at = Array.IndexOf(run.OutputLines, run.OutputLines.First(line => line.Contains(vault.Displayed(ConceptPath), StringComparison.Ordinal)));
        Assert.Contains("no `verified` key", run.OutputLines[at + 1], StringComparison.Ordinal);
    }

    /// <summary>
    /// The same inventory as the machine contract: the concept is one record of a bare array, and
    /// the record's own fields say it was generated by a tool and never verified.
    /// </summary>
    [SkippableFact]
    public void TheJsonInventoryCarriesTheConceptAsOneRecordOfTheArray()
    {
        using var vault = TheVault();
        var run = CliHarness.RunIn(vault.Root, vault.Home, "candidates", vault.Path, "--format", "json");

        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);
        using var document = JsonDocument.Parse(run.Output);
        Assert.Equal(JsonValueKind.Array, document.RootElement.ValueKind);

        var record = document.RootElement.EnumerateArray()
            .Single(element => element.GetProperty("path").GetString() == ConceptBundlePath);

        Assert.Equal(RowTrustTier(vault), record.GetProperty("trustTier").GetString());
        Assert.Equal(RowType(vault), record.GetProperty("type").GetString());

        // `generated` reaches the record unchanged: the actor and the instant are the file's own,
        // and the instant is the canonical form okf writes. Compared to the frontmatter rather
        // than to a format guess — the record and the file are one fact, and a writer that
        // reformatted it would be a second answer to what this concept's freshness is.
        Assert.Equal(StampActor(vault), record.GetProperty("generatedBy").GetString());
        Assert.Equal(StampText(vault), record.GetProperty("generatedAt").GetString());
        Assert.Matches(@"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$", record.GetProperty("generatedAt").GetString()!);

        // No verification fields at all (#77): a candidate has no events by construction, so an
        // always-null one would be a field a consumer has to disbelieve.
        Assert.False(record.TryGetProperty("verified", out _));
        Assert.False(record.TryGetProperty("verdict", out _));
    }

    /// <summary>
    /// The concept carries no verification events — not an empty list, not a stub. Those shapes
    /// are not equivalent to the verdict (<c>[]</c> is provable absence while <c>{}</c> is
    /// quarantined), so "no events" is asserted as the absence of the key itself.
    /// </summary>
    [SkippableFact]
    public void TheConceptCarriesNoVerificationEventsAndIsNotQuarantined()
    {
        using var vault = TheVault();

        Assert.DoesNotContain("verified", Frontmatter(vault), StringComparison.Ordinal);

        var run = CliHarness.RunIn(vault.Root, vault.Home, "candidates", vault.Path);

        // Quarantined is not the same as unlisted: a quarantine drops the concept from the
        // inventory and turns the run to exit 1, which is the failure this feature exists to make
        // impossible. The count is read off the command's own closing line, not typed.
        Assert.Matches(@"0 quarantined\.", Closing(run));
        Assert.DoesNotContain("could not classify", run.Error, StringComparison.Ordinal);
        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);
    }

    /// <summary>
    /// The stamp is written rather than typed: the <c>generated</c> line is exactly the flow
    /// mapping <c>okf generated stamp</c> emits, and re-stamping the file to a fixed instant moves
    /// that line and nothing else (AD-23, AD-52).
    /// </summary>
    /// <remarks>
    /// A hand-typed timestamp is indistinguishable from a written one by looking at its value, so
    /// the check is the verb's own signature instead: the actor quoted, because every §7 actor
    /// carries a colon and a plain scalar holding one is ambiguous in flow context. That quoting is
    /// what a person does not produce by typing a date, and it is the shape the vault's convention
    /// ("never hand-type <c>generated.at</c>") is supposed to guarantee.
    /// </remarks>
    [SkippableFact]
    public void TheStampOnTheConceptIsTheOneTheStampingVerbWrites()
    {
        using var vault = TheVault();

        Assert.Equal(
            OkfStamp.GeneratedEntry(
                StampActor(vault),
                DateTimeOffset.Parse(StampText(vault), CultureInfo.InvariantCulture)),
            GeneratedLine(vault));

        // Re-stamping to a fixed instant must move nothing else in the file. Run against a copy:
        // the vault on disk is the artifact under review, and a test that rewrote it would break
        // the index-drift gate sitting beside it in the same pipeline job.
        using var scratch = new TempTree();
        string copy = scratch.Write(
            Path.Combine("okf", ConceptPath),
            File.ReadAllText(Path.Combine(vault.Path, ConceptPath)));
        var run = CliHarness.RunIn(
            scratch.Root,
            scratch.Root,
            "generated",
            "stamp",
            copy,
            "--by",
            StampActor(vault),
            "--at",
            "2026-01-02T03:04:05Z");

        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);

        string[] original = File.ReadAllText(Path.Combine(vault.Path, ConceptPath))
            .ReplaceLineEndings("\n").Split('\n');
        string[] stamped = File.ReadAllText(copy).ReplaceLineEndings("\n").Split('\n');
        Assert.Equal(original.Length, stamped.Length);

        int line = GeneratedLineIndex(vault);
        for (var index = 0; index < original.Length; index++)
        {
            Assert.Equal(
                index == line
                    ? $"generated: {{ by: \"{StampActor(vault)}\", at: 2026-01-02T03:04:05Z }}"
                    : original[index],
                stamped[index]);
        }
    }

    /// <summary>
    /// The concept does not assert that the trust tier and the enumeration agree; where it
    /// describes their disagreement, it says the disagreement is designed.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A prohibition, and a prohibition cannot be checked by grepping for words: "the tier and the
    /// verdict do not agree" is the correct thing to say here, and "they are allowed to disagree" is
    /// correct too. So the assertion is anchored in the vocabulary the concept is written in: the
    /// sentence that states the relationship must carry the word for design, and the sentence that
    /// refuses to settle it must name the issue that owns the question.
    /// </para>
    /// <para>
    /// Three attempts at the general form were built and each was defeated by a one-word mutation,
    /// and the record is kept because the failure is not obvious. A deny/differ/assert trichotomy
    /// over the agreement vocabulary survived inserting "allowed"; demanding a negation or a "dis-"
    /// in the same sentence then survived inserting "not", and each widening excused the very
    /// mutation it had been written to catch. The general question — does this prose claim the two
    /// surfaces agree? — is a reading, and a reading is not something an assertion can hold.
    /// </para>
    /// <para>
    /// What it can hold is the pair of claims the acceptance criterion is actually about, each
    /// checked in the sentence that makes it: every sentence stating that the two surfaces part
    /// calls that parting designed, and the concept keeps its own refusal to claim agreement in
    /// place. The sentence splitter matters to the first of those — a footnote reference ends in a
    /// period, so an unguarded split carries "designed" from a citation into a sentence that never
    /// said it, and the assertion passes without the concept having claimed anything.
    /// </para>
    /// </remarks>
    [SkippableFact]
    public void TheConceptSaysTheDisagreementIsDesignedAndNamesWhoOwnsIt()
    {
        using var vault = TheVault();
        string prose = Unwrap(File.ReadAllText(Path.Combine(vault.Path, ConceptPath)));

        // The denial the acceptance criterion is written against, asserted as the sentence itself.
        // Paraphrase it away and this fails, which is the point: the criterion is that the concept
        // declines to claim the two agree, and the concept declines in these words.
        Assert.Matches(
            @"does not claim that the (trust )?tier and the enumeration agree, and it does not claim that they will be reconciled",
            prose);

        // Somewhere in the concept there must be ONE clause that both names the disagreement
        // between the two surfaces and calls it designed — the two halves of the acceptance
        // criterion carried by a single clause rather than assembled from neighbouring prose.
        //
        // This shape was arrived at by mutation, and each rejected shape is recorded because the
        // failure is not obvious. A file-wide search for "designed" passed on a concept that had
        // deleted the claim. A per-sentence check passed when the design claim was removed from
        // the clause stating the disagreement, because the NEXT sentence used the word. A
        // per-clause check demanding both in the same clause then failed on honest prose that
        // states the disagreement and attributes it to the design in two adjacent sentences —
        // prose that says the thing correctly. What survives is the reading the criterion asks
        // for: one clause that says "this disagreement is designed", with anaphora ("that",
        // "this") allowed to carry the reference.
        var disagreement = new Regex(@"disagree\w*", RegexOptions.IgnoreCase);

        // "by design" and "as a design" are deliberately NOT accepted: they are the preposition
        // form, and "rather than by design" in a neighbouring clause is a denial of design, not a
        // claim of it. Matching the phrase was shown to let the assertion pass on a concept whose
        // only remaining occurrence was exactly that denial.
        var design = new Regex(@"\bdesigned\b|\bdeliberate(?:ly)?\b", RegexOptions.IgnoreCase);

        bool statesItTogether = Clauses(prose).Any(clause =>
            disagreement.IsMatch(clause) && design.IsMatch(clause));

        Assert.True(
            statesItTogether,
            "the concept must carry one clause that names the tier/enumeration disagreement AND "
                + "calls it designed, rather than stating the two in separate prose");

        // And the open question stays open: the concept names the issue that owns the
        // reconciliation, so it is not a second answer to it.
        Assert.Matches(@"#84 owns that question", prose);
        Assert.DoesNotMatch(
            @"(?:the tier|tier and the enumeration)[^.]{0,40}\b(?:now|finally) reconciled\b",
            prose);
    }

    /// <summary>
    /// The concept follows the bundle's conventions for type, description, tags and citations, and
    /// the tags it uses are the ones this change registered.
    /// </summary>
    /// <remarks>
    /// <c>okf lint</c> enforces the shape of each of these over the whole vault and is the
    /// authority on them; what it cannot see is whether the citations are the work items the change
    /// answers to, or whether a new tag arrived in the same diff as the concept that needed it
    /// (practices/tagging-discipline.md rule 3). Those are what this asserts.
    /// </remarks>
    [SkippableFact]
    public void TheConceptFollowsTheBundleConventionsAndItsTagsAreRegistered()
    {
        using var vault = TheVault();
        string text = File.ReadAllText(Path.Combine(vault.Path, ConceptPath));

        Assert.Equal("Concept", Scalar(vault, "type"));
        Assert.NotEmpty(Scalar(vault, "description")!);

        var registry = TagRegistry(vault);
        var tags = Tags(vault);
        foreach (var tag in tags)
        {
            Assert.Contains(tag, registry, StringComparer.Ordinal);
        }

        // And the registry gained the word this concept introduces, in the same diff — rule 3 of
        // tagging discipline, which lint cannot see because it checks each concept against the
        // registry rather than the registry against the change. Dropping the tag from either side
        // has to be caught: from the concept, because the vocabulary would then hold a word
        // nothing uses; from the registry, because the concept would carry an unregistered tag.
        Assert.Contains("selfdoc", tags, StringComparer.Ordinal);
        Assert.Contains("selfdoc", registry, StringComparer.Ordinal);

        // Each source the concept declares is cited in prose by a footnote labelled with its own
        // id — the join key lint also checks, restated here because the ids worth citing on this
        // concept are specifically the work items it implements.
        var cited = Regex.Matches(text, @"\[\^([a-z0-9-]+)\](?!:)")
            .Select(match => match.Groups[1].Value)
            .ToHashSet(StringComparer.Ordinal);

        foreach (var id in new[] { "issue-81", "issue-71" })
        {
            Assert.Contains(id, SourceIds(vault), StringComparer.Ordinal);
            Assert.Contains(id, cited, StringComparer.Ordinal);
        }
    }

    /// <summary>
    /// The vault's own gate over the new concept: <c>okf lint</c> reports nothing at error,
    /// warning or info severity, and <c>index --check</c> says the generated indexes already
    /// describe the tree. Those are two of the three commands the CI <c>dogfood</c> job runs, so a
    /// regression here is a test failure rather than a red pipeline.
    /// </summary>
    [SkippableFact]
    public void TheVaultStillLintsCleanAndItsIndexesStillMatch()
    {
        using var vault = TheVault();

        var lint = CliHarness.RunIn(vault.Root, vault.Home, "lint", vault.Path);
        Assert.Equal(CliApplication.ExitSuccess, lint.ExitCode);
        Assert.Matches(@"0 errors, 0 warnings, 0 infos\.", lint.Summary);

        var indexes = CliHarness.RunIn(vault.Root, vault.Home, "index", "--check", vault.Bundle);
        Assert.Equal(CliApplication.ExitSuccess, indexes.ExitCode);
        Assert.Matches(@"0 drifted\.", indexes.Summary);

        // `okf lint`'s summary is the one the harness recognises; the candidate verb's own closing
        // line is the one that would say the same thing about a scan.
        var scan = CliHarness.RunIn(vault.Root, vault.Home, "candidates", vault.Path);
        Assert.Matches(@"0 quarantined\.", Closing(scan));
    }

    /// <summary>
    /// The checkout's vault, with a throwaway home directory so no machine configuration and no
    /// personal vault can widen what the scan sees.
    /// </summary>
    private static Vault TheVault()
    {
        var root = Repository.Root;
        Skip.If(root is null, "not running from a checkout");
        var path = Path.Combine(root!, "okf");
        Skip.IfNot(File.Exists(Path.Combine(path, ConceptPath)), $"no {ConceptPath} in the checkout");
        return new Vault(root!, path, Path.Combine(path, "bundles", "okf-net"));
    }

    private static string Text(Vault vault) => File.ReadAllText(Path.Combine(vault.Path, ConceptPath));

    private static string Frontmatter(Vault vault)
    {
        Match block = Regex.Match(Text(vault), @"\A---\n(.*?)\n---", RegexOptions.Singleline);
        Assert.True(block.Success, "the concept must open with a frontmatter block");
        return block.Groups[1].Value;
    }

    private static string? Scalar(Vault vault, string key)
    {
        Match match = Regex.Match(Frontmatter(vault), $@"^{key}: (.*)$", RegexOptions.Multiline);
        return match.Success ? Unquote(match.Groups[1].Value.Trim()) : null;
    }

    private static List<string> Tags(Vault vault)
    {
        Match match = Regex.Match(Frontmatter(vault), @"^tags: \[(.*)\]$", RegexOptions.Multiline);
        Assert.True(match.Success, "the concept must carry a flow-list `tags` value");
        return match.Groups[1].Value
            .Split(',')
            .Select(tag => Unquote(tag.Trim()))
            .Where(tag => tag.Length > 0)
            .ToList();
    }

    private static List<string> SourceIds(Vault vault) =>
        [.. Regex.Matches(Frontmatter(vault), @"^\s*- id: (.+)$", RegexOptions.Multiline)
            .Select(match => Unquote(match.Groups[1].Value.Trim()))];

    private static string GeneratedLine(Vault vault)
    {
        Match match = Regex.Match(Frontmatter(vault), @"^generated: (.*)$", RegexOptions.Multiline);
        Assert.True(match.Success, "the concept must carry a `generated` stamp");
        return match.Groups[1].Value;
    }

    private static int GeneratedLineIndex(Vault vault)
    {
        string[] lines = Text(vault).ReplaceLineEndings("\n").Split('\n');
        int index = Array.FindIndex(lines, line => line.StartsWith("generated: ", StringComparison.Ordinal));
        Assert.True(index >= 0, "the concept must carry a `generated` stamp");
        return index;
    }

    private static string StampActor(Vault vault) =>
        Unquote(Regex.Match(GeneratedLine(vault), @"by: (""[^""]*""|[^,}]+)").Groups[1].Value);

    private static string StampText(Vault vault) =>
        Regex.Match(GeneratedLine(vault), @"at: (\S+)").Groups[1].Value.TrimEnd('}').Trim();

    private static string RowType(Vault vault) => Scalar(vault, "type")!;

    /// <summary>
    /// The tier the concept derives, from the library that derives it rather than from the row it
    /// is compared against — otherwise the assertion would only be checking that a string equals
    /// itself.
    /// </summary>
    private static string RowTrustTier(Vault vault)
    {
        var document = OkfDocument.Parse(Text(vault));
        return new OkfConcept(
            new OkfBundle(vault.Bundle),
            Path.Combine(vault.Bundle, ConceptBundlePath),
            document,
            DateOnly.FromDateTime(DateTime.UtcNow)).TrustTier.ToSpecString();
    }

    /// <summary>
    /// The vault's tag registry, read the way okf reads it. <c>okf.json</c> is JSONC (AD-32), so
    /// this goes through <see cref="OkfConfig.Load" /> rather than a bare JSON parse: on the
    /// committed file a strict parse throws or yields nothing, and a registry read as empty turns
    /// every tag assertion below into a pass that measured nothing.
    /// </summary>
    private static List<string> TagRegistry(Vault vault)
    {
        var config = OkfConfig.Load(Path.Combine(vault.Path, OkfDiscovery.ConfigFileName));
        Assert.NotNull(config.TagRegistry);
        return [.. config.TagRegistry!];
    }

    private static string Unquote(string value) =>
        value.Length >= 2 && value[0] == '"' && value[^1] == '"'
            ? JsonElement.Parse($"\"{value[1..^1]}\"").GetString()!
            : value;

    /// <summary>
    /// A candidate run's closing line. <see cref="CliRun.Summary" /> recognises the summary
    /// prefixes of lint, index and search, and <c>Scanned</c> is deliberately not one of them —
    /// the harness assigns each prefix to one verb so a summary cannot be attributed to the wrong
    /// command — so the inventory's own line is taken from the tail of its stdout.
    /// </summary>
    private static string Closing(CliRun run) => run.OutputLines[^1];

    private static string Unwrap(string text) => Regex.Replace(text, @"\s*\n\s*", " ");

    /// <summary>
    /// The prose split into sentences, with the vault's own punctuation taken into account. Two
    /// shapes defeat a plain <c>(?&lt;=[.!?])</c> split and both appear in this concept: a footnote
    /// reference ends in a period (<c>[^issue-71]</c>), which would otherwise open the next
    /// sentence mid-citation and carry a word like "designed" into a sentence that never said it;
    /// and <c>§5.3</c> contains a period inside a clause. Both are removed before the split, so a
    /// sentence is the unit a claim is actually made in — which is what the disagreement assertion
    /// depends on to keep "designed" in the clause that earned it.
    /// </summary>
    /// <summary>
    /// The prose split at clause boundaries — the sentence splitter's output further divided on
    /// colon, semicolon, em dash, and comma. The disagreement assertion needs this narrower unit:
    /// a sentence is long enough to hold the design claim in one clause and the disagreement in
    /// another, and then pass while the two have drifted apart in the prose.
    /// </summary>
    private static IEnumerable<string> Clauses(string unwrapped) => Sentences(unwrapped)
        .SelectMany(sentence => Regex.Split(sentence, @"(?::|;|—|,)\s+"))
        .Select(clause => clause.Trim())
        .Where(clause => clause.Length > 0);

    private static IEnumerable<string> Sentences(string unwrapped)
    {
        string text = unwrapped.Replace("```", " ").Replace("`", string.Empty);
        text = Regex.Replace(text, @"\[\^[a-z0-9-]+\]", " ");
        text = text.Replace("§", "§ ");
        return Regex.Split(text, @"(?<=[.!?])\s+")
            .Select(sentence => sentence.Trim())
            .Where(sentence => sentence.Length > 0);
    }

    /// <summary>One concept's frontmatter read as text, plus the paths a run is issued against.</summary>
    private sealed class Vault(string root, string path, string bundle) : IDisposable
    {
        /// <summary>The repository root, which is the working directory a run is issued from.</summary>
        public string Root { get; } = root;

        /// <summary>The vault directory, <c>okf/</c>.</summary>
        public string Path { get; } = path;

        /// <summary>The bundle root inside it.</summary>
        public string Bundle { get; } = bundle;

        /// <summary>A home directory holding no okf configuration, so scope cannot widen.</summary>
        public string Home { get; } = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "okf-dogfood-home", System.IO.Path.GetRandomFileName());

        /// <summary>The path a candidate row prints for a file in this vault.</summary>
        public string Displayed(string vaultRelativePath) => System.IO.Path.Combine("okf", vaultRelativePath);

        public void Dispose()
        {
            if (Directory.Exists(Home))
            {
                Directory.Delete(Home, recursive: true);
            }
        }
    }
}
