using System.Xml;
using System.Xml.Linq;

namespace Okf.Core.Tests.Site;

/// <summary>
/// A bundle covering the metadata shapes <see cref="SiteFixture" /> does not: a concept with
/// no <c>type</c>, a deprecated one, a <c>generated</c> event naming no actor, and a
/// <c>sources</c> list carrying one entry of every shape §5.1 permits.
/// </summary>
internal sealed class MetadataFixture : IDisposable
{
    private readonly TempBundle _bundle;

    /// <summary>Builds the fixture bundle.</summary>
    public MetadataFixture()
    {
        _bundle = new TempBundle("meta");

        _bundle
            .Add("index.md", """
                # Concept

                * [Sourced](sourced.md) - sourced
                """)
            .Add("sourced.md", """
                ---
                type: Concept
                title: Sourced
                verified: { by: "human:ringo", at: 2026-05-02 }
                sources:
                  - id: web
                    title: The web source
                    resource: https://example.invalid/web
                    author: "human:ringo"
                    last_modified: 2026-04-01
                    usage_count: 12
                  - id: file
                    title: The local note
                    resource: notes/thing.md
                    author: "process:crawler"
                  - id: scope
                    resource: all queries in project X
                  - id: bare
                  - title: Anonymous
                ---

                Sourced cites the web source.[^web]

                [^web]: The web source, §5.1.
                """)
            .Add("deprecated.md", """
                ---
                type: Reference
                title: Deprecated
                status: deprecated
                ---

                Deprecated.
                """)
            .Add("plain.md", """
                ---
                title: Plain
                ---

                Plain names no type, records no generated event and has no verifier.
                """)
            .Add("anon.md", """
                ---
                type: Concept
                title: Anon
                generated: { at: 2026-05-04 }
                ---

                Anon was generated by nobody in particular.
                """);
    }

    /// <summary>The working set a command would resolve for the fixture.</summary>
    public OkfWorkingSet WorkingSet =>
        new([_bundle.Bundle], null, $"bundle '{_bundle.Root}' (fixture)");

    /// <summary>Renders the site.</summary>
    /// <returns>The plan.</returns>
    public OkfSitePlan Plan() =>
        OkfSiteGenerator.Plan(
            WorkingSet,
            new OkfSiteOptions { Today = SiteFixture.Today, Name = "Meta" });

    /// <inheritdoc />
    public void Dispose() => _bundle.Dispose();
}

/// <summary>
/// The panels a concept page carries beside its body: the classification facts, "About this
/// page", the sources list and the backlinks.
/// </summary>
/// <remarks>
/// <para>Read off the parsed document rather than off the markup text, so an assertion says
/// what a reader is shown — which tone, which glyph, which word, in which order — instead of
/// pinning whitespace. Every expected row is derived from the fixture's own frontmatter and
/// the spec section it comes from, never from the generator's output.</para>
/// <para><b>AD-40</b>: colour is a status channel and never the only one, so every status
/// arrives with a tone, a glyph and a word. Asserting the three together is what makes a page
/// that quietly lost one of them go red.</para>
/// </remarks>
public class OkfSitePanelTests
{
    [Fact]
    public void ClassificationFactsAreTheFrontmattersOwnReadings()
    {
        using var fixture = new SiteFixture();
        var plan = fixture.Plan();

        // §4.1's `type` is a reading with no status attached, so it carries no tone and no
        // glyph; §5.3's tier is the opposite, and each of the three tiers has its own pair.
        Assert.Equal(
            ["-|Type|plain:Concept", "tone-neutral|Trust|signal:tone-neutral:○:unverified"],
            Facts(Page(plan, "kb/hub.html")));
        Assert.Equal(
            ["-|Type|plain:Concept", "tone-good|Trust|signal:tone-good:✔:human-reviewed"],
            Facts(Page(plan, "kb/reviewed.html")));
        Assert.Equal(
            ["-|Type|plain:Concept", "tone-warning|Trust|signal:tone-warning:◎:machine-confirmed"],
            Facts(Page(plan, "kb/confirmed.html")));
    }

    [Fact]
    public void StalenessAndLifecycleEachGetTheirOwnFactOrNone()
    {
        using var fixture = new SiteFixture();
        var plan = fixture.Plan();

        // §5.5: past its `stale_after` a page says so and says since when; before it, the
        // same date is a reassurance rather than a warning and the tone turns with it.
        Assert.Equal(
            [
                "-|Type|plain:Reference",
                "tone-neutral|Trust|signal:tone-neutral:○:unverified",
                "tone-critical|Stale|signal:tone-critical:△:since 2026-01-01",
            ],
            Facts(Page(plan, "kb/expired.html")));
        Assert.Equal(
            [
                "-|Type|plain:Reference",
                "tone-neutral|Trust|signal:tone-neutral:○:unverified",
                "tone-neutral|Fresh until|signal:tone-neutral:△:2027-01-01",
            ],
            Facts(Page(plan, "kb/fresh.html")));

        // §5.4: `draft` and `deprecated` are the two statuses worth stating. `stable` is the
        // default every concept without a `status` key already has, and a fact stating it
        // would be a badge for having said nothing.
        Assert.Equal(
            [
                "-|Type|plain:Concept",
                "tone-neutral|Trust|signal:tone-neutral:○:unverified",
                "tone-serious|Status|signal:tone-serious:✎:draft",
            ],
            Facts(Page(plan, "kb/rough.html")));

        using var metadata = new MetadataFixture();
        var meta = metadata.Plan();
        Assert.Equal(
            [
                "-|Type|plain:Reference",
                "tone-neutral|Trust|signal:tone-neutral:○:unverified",
                "tone-neutral|Status|signal:tone-neutral:✖:deprecated",
            ],
            Facts(Page(meta, "meta/deprecated.html")));

        // A concept that states no type states the readings it has and invents none.
        Assert.Equal(
            ["tone-neutral|Trust|signal:tone-neutral:○:unverified"],
            Facts(Page(meta, "meta/plain.html")));
    }

    [Fact]
    public void TheAboutPanelStatesEveryReadingIncludingTheAbsentOnes()
    {
        using var fixture = new SiteFixture();
        var plan = fixture.Plan();

        // §5.2's two events under §7's actor convention: a `human:` actor is the good tone
        // and a tick, anything else is neutral and a ring. An event the frontmatter never
        // recorded is stated as absent rather than dropped — this panel is the full reading,
        // and "not verified" is the answer a reader came here for.
        Assert.Equal(
            [
                "Type|plain:Concept",
                "Status|plain:stable",
                "Trust|signal:tone-neutral:○:unverified",
                "Generated|signal:tone-neutral:◎:claude-fable/5 · 2026-05-01",
                "Verified|empty",
                "Bundle|plain:kb",
                "Path|plain:hub.md",
            ],
            About(Page(plan, "kb/hub.html")));

        Assert.Equal(
            [
                "Type|plain:Concept",
                "Status|plain:stable",
                "Trust|signal:tone-good:✔:human-reviewed",
                "Generated|empty",
                "Verified|signal:tone-good:✔:human:ringo · 2026-05-02",
                "Bundle|plain:kb",
                "Path|plain:reviewed.md",
            ],
            About(Page(plan, "kb/reviewed.html")));

        Assert.Equal(
            [
                "Type|plain:Concept",
                "Status|plain:stable",
                "Trust|signal:tone-warning:◎:machine-confirmed",
                "Generated|empty",
                "Verified|signal:tone-neutral:◎:process:nightly · 2026-05-03",
                "Bundle|plain:kb",
                "Path|plain:confirmed.md",
            ],
            About(Page(plan, "kb/confirmed.html")));

        // §5.5 again, in the panel's own wording: one date, read two ways.
        Assert.Contains("Stale since|signal:tone-critical:△:2026-01-01", About(Page(plan, "kb/expired.html")));
        Assert.Contains("Fresh until|signal:tone-neutral:△:2027-01-01", About(Page(plan, "kb/fresh.html")));
        Assert.Contains("Status|signal:tone-serious:✎:draft", About(Page(plan, "kb/rough.html")));
    }

    [Fact]
    public void AnEventThatNamesNoActorIsNoEvent()
    {
        using var metadata = new MetadataFixture();
        var plan = metadata.Plan();

        // §5.2 makes `by` the event: a `generated` mapping carrying only an `at` names
        // nobody, so the panel says nobody rather than rendering an actor with no name.
        Assert.Contains("Generated|empty", About(Page(plan, "meta/anon.html")));
        Assert.Contains("Type|empty", About(Page(plan, "meta/plain.html")));
    }

    [Fact]
    public void EverySourceShapeSection51PermitsRendersAsItself()
    {
        using var metadata = new MetadataFixture();
        var sources = Sources(Page(metadata.Plan(), "meta/sourced.html"));

        // A `resource` that is a followable URL becomes the title's own link, opened away
        // from the site; author, recency and adoption each arrive with a glyph as well as a
        // hue (AD-40); and §5.1's footnote join points back into the body.
        Assert.Equal(
            "src-web|link:https://example.invalid/web:The web source|"
            + "signal:tone-good:✔:human:ringo;signal:tone-neutral:↻:modified 2026-04-01;"
            + "signal:tone-neutral:∑:used 12;cite:#fn:1:cited as [^web]",
            sources[0]);

        // A `resource` that is not a URL is never an anchor — a relative path in an href on
        // a `file://` page points at whatever happens to sit beside the output. It is shown
        // under the title when it says something the title does not.
        Assert.Equal(
            "src-file|text:The local note|path:notes/thing.md|"
            + "signal:tone-neutral:◎:process:crawler;signal:tone-neutral:-:not cited in the body",
            sources[1]);

        // With no `title`, the `resource` is the label — and it is then not repeated under
        // itself.
        Assert.Equal(
            "src-scope|text:all queries in project X|signal:tone-neutral:-:not cited in the body",
            sources[2]);

        // With neither, the `id` is all there is to show.
        Assert.Equal(
            "src-bare|text:bare|signal:tone-neutral:-:not cited in the body",
            sources[3]);

        // §5.1 makes `id` the join key, so an entry without one joins to nothing: it gets no
        // anchor to be linked at, and it cannot be reported as uncited because nothing could
        // have cited it.
        Assert.Equal("-|text:Anonymous|", sources[4]);
    }

    [Fact]
    public void TheBacklinksPanelNamesEveryConceptThatCitesThePage()
    {
        using var fixture = new SiteFixture();
        var plan = fixture.Plan();

        // The inverse of the bodies' own links, and the one panel built from other pages:
        // each entry is a link to the citing concept plus the id a reader can grep for.
        Assert.Equal(
            ["Nested|kb/deep/nested", "Reviewed|kb/reviewed"],
            Backlinks(Page(plan, "kb/hub.html")).Order(StringComparer.Ordinal));

        // Nothing cites `fresh.md`, so it carries no panel at all rather than an empty one.
        // An empty list would satisfy `Backlinks` too, so the absence is asserted on the
        // section: a heading over nothing tells the reader a question was asked and answered
        // "nobody", where the page in fact never asked it.
        Assert.Null(Panel(Page(plan, "kb/fresh.html"), "Cited by"));
    }

    private static XDocument Page(OkfSitePlan plan, string path)
    {
        using var reader = XmlReader.Create(
            new StringReader(plan.Files.Single(file => file.Path == path).Content),
            new XmlReaderSettings { DtdProcessing = DtdProcessing.Ignore, XmlResolver = null });

        return XDocument.Load(reader);
    }

    private static string[] Classes(XElement element) =>
        (element.Attribute("class")?.Value ?? string.Empty).Split(' ', StringSplitOptions.RemoveEmptyEntries);

    private static bool Has(XElement element, string name) =>
        Classes(element).Contains(name, StringComparer.Ordinal);

    private static string Tone(XElement element) =>
        Classes(element).FirstOrDefault(name => name.StartsWith("tone-", StringComparison.Ordinal)) ?? "-";

    /// <summary>The text an element carries itself, without its children's.</summary>
    private static string OwnText(XElement element) =>
        string.Concat(element.Nodes().OfType<XText>().Select(node => node.Value));

    /// <summary>
    /// One rendered value as <c>plain:…</c>, <c>empty</c>, or
    /// <c>signal:&lt;tone&gt;:&lt;glyph&gt;:&lt;word&gt;</c>.
    /// </summary>
    private static string Value(XElement container)
    {
        if (container.Elements("span").FirstOrDefault(span => Has(span, "signal")) is { } signal)
        {
            return $"signal:{Tone(signal)}:{Glyph(signal)}:{OwnText(signal)}";
        }

        return container.Elements("span").Any(span => Has(span, "empty"))
            ? "empty"
            : $"plain:{container.Value}";
    }

    private static string Glyph(XElement signal) =>
        signal.Elements("span").FirstOrDefault(span => Has(span, "glyph"))?.Value ?? "-";

    /// <summary>Every classification fact, as <c>&lt;tone&gt;|&lt;key&gt;|&lt;value&gt;</c>.</summary>
    private static IEnumerable<string> Facts(XDocument page) =>
        page.Descendants("dl")
            .Where(list => Has(list, "facts"))
            .SelectMany(list => list.Elements("div").Where(fact => Has(fact, "fact")))
            .Select(fact => $"{Tone(fact)}|{fact.Element("dt")!.Value}|{Value(fact.Element("dd")!)}");

    /// <summary>Every "About this page" row, as <c>&lt;key&gt;|&lt;value&gt;</c>.</summary>
    private static IReadOnlyList<string> About(XDocument page)
    {
        var panel = Panel(page, "About this page")!.Element("dl")!;
        return
        [
            .. panel.Elements("dt")
                .Zip(panel.Elements("dd"), (term, definition) => $"{term.Value}|{Value(definition)}"),
        ];
    }

    /// <summary>Every sources entry, flattened to its anchor, its label, its path and its signals.</summary>
    private static IReadOnlyList<string> Sources(XDocument page)
    {
        var list = Panel(page, "Sources")?.Element("ul");
        return list is null ? [] :
        [
            .. list.Elements("li").Select(entry =>
            {
                var title = entry.Elements("div").First(part => Has(part, "source-title"));
                var path = entry.Elements("div").FirstOrDefault(part => Has(part, "path"));
                var signals = entry.Elements("div").First(part => Has(part, "signals")).Elements()
                    .Select(signal => signal.Name.LocalName == "a"
                        ? $"cite:{signal.Attribute("href")!.Value}:{signal.Value}"
                        : $"signal:{Tone(signal)}:{Glyph(signal)}:{OwnText(signal)}");

                var parts = (string?[])
                [
                    entry.Attribute("id")?.Value ?? "-",
                    title.Element("a") is { } anchor
                        ? $"link:{anchor.Attribute("href")!.Value}:{anchor.Value}"
                        : $"text:{title.Value}",
                    path is null ? null : $"path:{path.Value}",
                    string.Join(';', signals),
                ];

                return string.Join('|', parts.Where(part => part is not null));
            }),
        ];
    }

    /// <summary>Every "Cited by" entry, as <c>&lt;title&gt;|&lt;id&gt;</c>.</summary>
    private static IReadOnlyList<string> Backlinks(XDocument page)
    {
        var list = Panel(page, "Cited by")?.Element("ul");
        return list is null ? [] :
        [
            .. list.Elements("li").Select(entry =>
                $"{entry.Element("a")!.Value}|{entry.Elements("span").First(span => Has(span, "path")).Value}"),
        ];
    }

    private static XElement? Panel(XDocument page, string heading) =>
        page.Descendants("section")
            .SingleOrDefault(section => Has(section, "panel") && section.Element("h2")?.Value == heading);
}
