namespace Okf.Core.Tests.Site;

/// <summary>
/// A fixture vault whose trust, staleness and lifecycle values are chosen by hand, so the
/// dashboard's tile counts can be asserted against a tally taken from the frontmatter rather
/// than from the code that computes them.
/// </summary>
/// <remarks>
/// The tally, read straight off the documents below and OKF v0.2 §5.3/§5.4/§5.5:
/// <list type="bullet">
/// <item>7 concepts (<c>index.md</c> and <c>log.md</c> are reserved, §3.1, and are pages but
/// never concepts).</item>
/// <item>trust: <c>reviewed</c> has a <c>human:</c> verifier ⇒ human-reviewed;
/// <c>confirmed</c> has only a <c>process:</c> verifier ⇒ machine-confirmed; the other five
/// carry no <c>verified</c> key ⇒ unverified.</item>
/// <item>stale: <c>expired</c> has <c>stale_after: 2026-01-01</c> and the fixture's today is
/// 2026-06-01 ⇒ 1 stale. <c>fresh</c>'s 2027-01-01 is in the future ⇒ not stale.</item>
/// <item>draft: <c>rough</c> carries <c>status: draft</c> ⇒ 1 draft. Its description
/// carries a <c>&lt;</c> and an <c>&amp;</c> on purpose: those are the two characters that
/// break an embedded JSON payload out of the <c>&lt;script&gt;</c> element carrying it.</item>
/// </list>
/// </remarks>
internal sealed class SiteFixture : IDisposable
{
    private readonly TempBundle _bundle;

    /// <summary>Builds the fixture vault.</summary>
    public SiteFixture()
    {
        _bundle = new TempBundle("kb");

        _bundle
            .Add("index.md", """
                <!-- generated by okf -->

                # Concept

                * [Hub](hub.md) - the hub
                * [Reviewed](reviewed.md) - reviewed
                """)
            .Add("log.md", """
                # Directory Update Log

                ## 2026-05-22

                * Started.
                """)
            .Add("hub.md", """
                ---
                type: Concept
                title: Hub
                description: Links to everything.
                tags: [a, b]
                generated: { by: claude-fable/5, at: 2026-05-01 }
                sources:
                  - id: spec
                    resource: https://example.invalid/spec
                    title: The spec
                    author: "human:ringo"
                    last_modified: 2026-04-01
                  - id: unused
                    resource: all queries in project X
                ---

                Hub cites the spec.[^spec] It links to [reviewed](reviewed.md), to
                [nested](deep/nested.md), to [expired](/expired.md) and to
                [nothing](missing.md). It also links [outside](https://example.invalid/).

                [^spec]: The spec, §5.
                """)
            .Add("reviewed.md", """
                ---
                type: Concept
                title: Reviewed
                verified: { by: "human:ringo", at: 2026-05-02 }
                ---

                Reviewed links back to [hub](hub.md).
                """)
            .Add("confirmed.md", """
                ---
                type: Concept
                title: Confirmed
                verified:
                  - { by: "process:nightly", at: 2026-05-03 }
                ---

                Confirmed stands alone.
                """)
            .Add("expired.md", """
                ---
                type: Reference
                title: Expired
                stale_after: 2026-01-01
                ---

                Expired.
                """)
            .Add("fresh.md", """
                ---
                type: Reference
                title: Fresh
                stale_after: 2027-01-01
                ---

                Fresh.
                """)
            .Add("rough.md", """
                ---
                type: Concept
                title: Rough
                status: draft
                description: Draft notes on <tags> & ampersands.
                ---

                Rough.
                """)
            .Add("deep/nested.md", """
                ---
                type: Concept
                title: Nested
                ---

                Nested links up to [hub](../hub.md).
                """)
            .Add("deep/index.md", """
                <!-- generated by okf -->

                # Concept

                * [Nested](nested.md) - nested
                """);
    }

    /// <summary>The date the fixture judges staleness against.</summary>
    public static DateOnly Today => new(2026, 6, 1);

    /// <summary>The bundle root.</summary>
    public string Root => _bundle.Root;

    /// <summary>The working set a command would resolve for the fixture.</summary>
    public OkfWorkingSet WorkingSet =>
        new([_bundle.Bundle], null, $"bundle '{_bundle.Root}' (fixture)");

    /// <summary>Builds the site model.</summary>
    /// <param name="singleFile">Whether to resolve links for the single-file emitter.</param>
    /// <returns>The model.</returns>
    public OkfSiteModel Build(bool singleFile = false) =>
        OkfSiteBuilder.Build(WorkingSet, Options(singleFile));

    /// <summary>Renders the site.</summary>
    /// <param name="singleFile">Whether to emit one file instead of a page per concept.</param>
    /// <returns>The plan.</returns>
    public OkfSitePlan Plan(bool singleFile = false) =>
        OkfSiteGenerator.Plan(WorkingSet, Options(singleFile));

    /// <inheritdoc />
    public void Dispose() => _bundle.Dispose();

    private static OkfSiteOptions Options(bool singleFile) => new()
    {
        Today = Today,
        SingleFile = singleFile,
        Name = "Fixture",
    };
}
