# okf completion for PowerShell. Generated by `okf completion pwsh`; do not edit.
#
# Load it into this session:  okf completion pwsh | Out-String | Invoke-Expression
# Install it permanently:     add that line to your $PROFILE

Register-ArgumentCompleter -Native -CommandName okf -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $words = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })
    $valueFlags = @('--at', '--bundle', '--by', '--captured-at', '--channel', '--concept', '--config', '--dir', '--form', '--format', '--generated-at', '--host', '--limit', '--name', '--out', '--scope', '--severity', '--source-last-modified', '--tag', '--title', '--type', '--url', '--verify', '--version', '-o')

    # The verb and its subcommand are the first two bare words that are not some
    # flag's value.
    $verb = ''
    $sub = ''
    $skip = $false
    if ($words.Count -gt 1) {
        foreach ($word in $words[1..($words.Count - 1)]) {
            if ($skip) { $skip = $false; continue }
            if ($word -like '--*=*') { continue }
            if ($valueFlags -contains $word) { $skip = $true; continue }
            if ($word -like '-*') { continue }
            if (-not $verb) { $verb = $word } elseif (-not $sub) { $sub = $word }
        }
    }
    if ($words.Count -gt 1 -and $wordToComplete) {
        # The word under the cursor is not a decided verb yet.
        if ($sub -eq $wordToComplete) { $sub = '' } elseif ($verb -eq $wordToComplete) { $verb = '' }
    }

    $previous = ''
    if ($words.Count -gt 1) {
        $previous = if ($wordToComplete) { $words[$words.Count - 2] } else { $words[$words.Count - 1] }
    }

    $candidates = @()
    switch ($verb) {
        'init' {
            switch ($previous) {
                '--name' { $candidates = @() }
                default { $candidates = @('--help', '-h', '--name', '--no-agents-md', '--personal', '--verbose', '-v') }
            }
        }
        'lint' {
            switch ($previous) {
                '--config' { $candidates = @() }
                '--format' { $candidates = @('json', 'text') }
                '--severity' { $candidates = @('OKF0001', 'OKF0002', 'OKF0003', 'OKF0004', 'OKF0101', 'OKF0102', 'OKF0103', 'OKF0201', 'OKF0202', 'OKF0301', 'OKF0302', 'OKF0303', 'OKF0304', 'OKF0305', 'OKF0306', 'OKF0307', 'OKF0308', 'OKF0309', 'OKF0310') }
                default { $candidates = @('--help', '-h', '--config', '--format', '--json', '--list-rules', '--severity', '--treat-all-warnings-as-errors', '--verbose', '-v') }
            }
        }
        'index' {
            switch ($previous) {
                '--format' { $candidates = @('json', 'text') }
                default { $candidates = @('--help', '-h', '--check', '--format', '--json', '--verbose', '-v') }
            }
        }
        'search' {
            switch ($previous) {
                '--format' { $candidates = @('json', 'text') }
                '--limit' { $candidates = @() }
                '--tag' { $candidates = @() }
                '--type' { $candidates = @() }
                '--scope' { $candidates = @('project', 'personal', 'registered', 'all') }
                default { $candidates = @('--help', '-h', '--format', '--json', '--limit', '--scope', '--tag', '--type', '--verbose', '-v') }
            }
        }
        'register' {
            switch ($previous) {
                '--format' { $candidates = @('json', 'text') }
                default { $candidates = @('--help', '-h', '--format', '--json', '--verbose', '-v') }
            }
        }
        'unregister' {
            switch ($previous) {
                '--format' { $candidates = @('json', 'text') }
                default { $candidates = @('--help', '-h', '--format', '--json', '--verbose', '-v') }
            }
        }
        'registry' {
            switch ($previous) {
                '--format' { $candidates = @('json', 'text') }
                default { $candidates = @('--help', '-h', '--format', '--json', '--verbose', '-v', 'list', 'prune') }
            }
        }
        'inbox' {
            switch ($previous) {
                '--format' { $candidates = @('json', 'text') }
                default { $candidates = @('--help', '-h', '--fail-if-any', '--format', '--json', '--verbose', '-v') }
            }
        }
        'candidates' {
            switch ($previous) {
                '--format' { $candidates = @('json', 'text') }
                default { $candidates = @('--help', '-h', '--format', '--json', '--verbose', '-v') }
            }
        }
        'verify' {
            switch ($previous) {
                '--by' { $candidates = @() }
                '--config' { $candidates = @() }
                default { $candidates = @('--help', '-h', '--by', '--config', '--dry-run', '--verbose', '-v') }
            }
        }
        'capture' {
            switch ($previous) {
                '--at' { $candidates = @() }
                '--by' { $candidates = @() }
                '--captured-at' { $candidates = @() }
                '--source-last-modified' { $candidates = @() }
                '--title' { $candidates = @() }
                '--url' { $candidates = @() }
                '--concept' { $candidates = @() }
                '--form' { $candidates = @('flat', 'packet') }
                default { $candidates = @('--help', '-h', '--at', '--by', '--captured-at', '--concept', '--form', '--json', '--source-last-modified', '--title', '--url', 'add', 'close') }
            }
        }
        'generated' {
            switch ($previous) {
                '--at' { $candidates = @() }
                '--by' { $candidates = @() }
                default { $candidates = @('--help', '-h', '--at', '--by', '--dry-run', 'stamp') }
            }
        }
        'bundle' {
            switch ($previous) {
                '--bundle' { $candidates = @() }
                '--generated-at' { $candidates = @() }
                '--format' { $candidates = @('dir', 'tar.gz', 'zip') }
                '--out' { $candidates = @() }
                '-o' { $candidates = @() }
                '--verify' { $candidates = @() }
                default { $candidates = @('--help', '-h', '--bundle', '--format', '--generated-at', '--lint', '--out', '-o', '--verify', '--verbose', '-v') }
            }
        }
        'site' {
            switch ($previous) {
                '--format' { $candidates = @('json', 'text') }
                '--name' { $candidates = @() }
                '--out' { $candidates = @() }
                '-o' { $candidates = @() }
                default { $candidates = @('--help', '-h', '--format', '--json', '--name', '--out', '-o', '--single-file', '--verbose', '-v') }
            }
        }
        'skills' {
            switch ($previous) {
                '--dir' { $candidates = @() }
                '--host' { $candidates = @('all', 'claude', 'generic', 'pi') }
                '--scope' { $candidates = @('project', 'user') }
                default { $candidates = @('--help', '-h', '--dir', '--force', '--host', '--names', '--no-agents-md', '--scope', 'install', 'list', 'path') }
            }
            if (-not $previous.StartsWith('-') -and $sub -eq 'path') {
                $candidates += @(& okf skills list --names 2>$null)
            }
        }
        'mcp' {
            switch ($previous) {
                '--scope' { $candidates = @('project', 'personal', 'registered', 'all') }
                default { $candidates = @('--help', '-h', '--scope', '--verbose', '-v') }
            }
        }
        'upgrade' {
            switch ($previous) {
                '--channel' { $candidates = @('rc', 'stable') }
                '--format' { $candidates = @('json', 'text') }
                '--version' { $candidates = @() }
                default { $candidates = @('--help', '-h', '--channel', '--check', '--dry-run', '--format', '--json', '--version') }
            }
        }
        'completion' {
            switch ($previous) {
                default { $candidates = @('--help', '-h') }
            }
            if (-not $previous.StartsWith('-')) {
                $candidates += @('bash', 'fish', 'pwsh', 'zsh')
            }
        }
        'help' {
            switch ($previous) {
                default { $candidates = @() }
            }
        }
        'version' {
            switch ($previous) {
                default { $candidates = @('--verbose', '-v') }
            }
        }
        default { $candidates = @('init', 'lint', 'index', 'search', 'register', 'unregister', 'registry', 'inbox', 'candidates', 'verify', 'capture', 'generated', 'bundle', 'site', 'skills', 'mcp', 'upgrade', 'completion', 'help', 'version') }
    }

    $candidates |
        Where-Object { $_ -like "$wordToComplete*" } |
        Sort-Object -Unique |
        ForEach-Object {
            [System.Management.Automation.CompletionResult]::new(
                $_, $_, 'ParameterValue', $_)
        }
}
