#compdef okf
# okf completion for zsh. Generated by `okf completion zsh`; do not edit.
#
# Load it into this shell:  eval "$(okf completion zsh)"
# Install it permanently:   okf completion zsh > \
#     "${XDG_DATA_HOME:-$HOME/.local/share}/zsh/site-functions/_okf"
# (that directory has to be on $fpath before compinit runs)

__okf_skill_names() {
    local -a names
    names=(${(f)"$(okf skills list --names 2>/dev/null)"})
    compadd -a names
}

_okf() {
    local cur prev verb sub word index skip
    local -a verbs options
    cur="${words[CURRENT]}"
    prev=""
    (( CURRENT > 1 )) && prev="${words[CURRENT-1]}"

    # The verb and its subcommand are the first two bare words that are not some
    # flag's value, which is why the value-taking flags are listed here.
    verb=""
    sub=""
    skip=0
    index=2
    while (( index < CURRENT )); do
        word="${words[index]}"
        (( index++ ))
        if (( skip )); then
            skip=0
            continue
        fi
        case "$word" in
            (--*=*) ;;
            (--at|--bundle|--by|--captured-at|--channel|--concept|--config|--dir|--form|--format|--generated-at|--host|--limit|--name|--out|--scope|--severity|--source-last-modified|--tag|--title|--type|--url|--verify|--version|-o) skip=1 ;;
            (-*) ;;
            (*)
                if [[ -z "$verb" ]]; then
                    verb="$word"
                elif [[ -z "$sub" ]]; then
                    sub="$word"
                fi
                ;;
        esac
    done

    if [[ -z "$verb" ]]; then
        verbs=(
            'init:Scaffold a vault'
            'lint:Validate conformance plus the configured warning set'
            'index:Generate the index.md files for a bundle'
            'search:Search the resolved bundles'
            'register:Add a vault or bundle to the registry'
            'unregister:Remove a registry entry'
            'registry:Report the registry or drop entries whose path is gone'
            'inbox:List the concepts waiting on a person'
            'candidates:List the concepts nobody has ever verified'
            'verify:Stamp human verification on one or more concepts'
            'capture:Record a raw/ capture or close its ingestion'
            'generated:Write the generated stamp a producer owes'
            'bundle:Package the bundles for consume-only distribution'
            'site:Render the bundles as a static site'
            'skills:The agent skills this binary carries and where they install'
            'mcp:Run the read-only MCP server over stdio'
            'upgrade:Replace this binary with the newest release'
            'completion:Print a shell completion script'
            'help:Show the verb list'
            'version:Show the version'
        )
        _describe -t verbs 'okf verb' verbs
        return
    fi

    case "$verb" in
        (init)
            case "$prev" in
                (--name) return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--name:The bundle directory to create'
                    '--no-agents-md:Skip writing the AGENTS.md/CLAUDE.md pointer'
                    '--personal:Scaffold the personal vault rather than a project one'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            _files
            ;;
        (lint)
            case "$prev" in
                (--config) _files; return ;;
                (--format) compadd -- json text; return ;;
                (--severity) compadd -- OKF0001 OKF0002 OKF0003 OKF0004 OKF0101 OKF0102 OKF0103 OKF0201 OKF0202 OKF0301 OKF0302 OKF0303 OKF0304 OKF0305 OKF0306 OKF0307 OKF0308 OKF0309 OKF0310; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--config:Read this project config instead of the vault config'
                    '--format:Output format'
                    '--json:Emit the stable JSON form instead of text'
                    '--list-rules:Print the rule catalog and stop'
                    '--severity:Override the severity of one rule as OKF####=level'
                    '--treat-all-warnings-as-errors:Promote every warning to an error'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            _files
            ;;
        (index)
            case "$prev" in
                (--format) compadd -- json text; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--check:Write nothing and fail on drift'
                    '--format:Output format'
                    '--json:Emit the stable JSON form instead of text'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            _files
            ;;
        (search)
            case "$prev" in
                (--format) compadd -- json text; return ;;
                (--limit|--tag|--type) return ;;
                (--scope) compadd -- project personal registered all; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--format:Output format'
                    '--json:Emit the stable JSON form instead of text'
                    '--limit:How many results to report at most'
                    '--scope:Which bundles the search covers'
                    '--tag:Only concepts carrying this tag'
                    '--type:Only concepts of this type'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            ;;
        (register)
            case "$prev" in
                (--format) compadd -- json text; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--format:Output format'
                    '--json:Emit the stable JSON form instead of text'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            _files
            ;;
        (unregister)
            case "$prev" in
                (--format) compadd -- json text; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--format:Output format'
                    '--json:Emit the stable JSON form instead of text'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            _files
            ;;
        (registry)
            case "$prev" in
                (--format) compadd -- json text; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--format:Output format'
                    '--json:Emit the stable JSON form instead of text'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            if [[ -z "$sub" ]]; then
                compadd -- list prune
                return
            fi
            ;;
        (inbox)
            case "$prev" in
                (--format) compadd -- json text; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--fail-if-any:Exit 1 when the inbox is not empty'
                    '--format:Output format'
                    '--json:Emit the stable JSON form instead of text'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            _files
            ;;
        (candidates)
            case "$prev" in
                (--format) compadd -- json text; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--format:Output format'
                    '--json:Emit the stable JSON form instead of text'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            _files
            ;;
        (verify)
            case "$prev" in
                (--by) return ;;
                (--config) _files; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--by:Stamp this actor instead of the resolved identity'
                    '--config:Read verify.actor from this project config'
                    '--dry-run:Report what would be written and write nothing'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            _files
            ;;
        (capture)
            case "$prev" in
                (--at|--by|--captured-at|--source-last-modified|--title|--url) return ;;
                (--concept) _files; return ;;
                (--form) compadd -- flat packet; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--at:Alias of --captured-at'
                    '--by:The capturing or ingesting actor'
                    '--captured-at:Pin the capture instant'
                    '--concept:A concept the ingestion produced'
                    '--form:The shape the item takes on disk'
                    '--json:Emit the stable JSON form instead of text'
                    '--source-last-modified:The last-modified date the artifact itself carries'
                    '--title:The title of the captured artifact'
                    '--url:The URL the artifact came from'
                )
                _describe -t options 'option' options
                return
            fi
            if [[ -z "$sub" ]]; then
                compadd -- add close
                return
            fi
            _files
            ;;
        (generated)
            case "$prev" in
                (--at|--by) return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--at:Pin the stamp instant'
                    '--by:The generating actor'
                    '--dry-run:Report what would be written and write nothing'
                )
                _describe -t options 'option' options
                return
            fi
            if [[ -z "$sub" ]]; then
                compadd -- stamp
                return
            fi
            _files
            ;;
        (bundle)
            case "$prev" in
                (--bundle|--generated-at) return ;;
                (--format) compadd -- dir tar.gz zip; return ;;
                (--out|-o|--verify) _files; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--bundle:Package only this bundle'
                    '--format:The distribution shape to write'
                    '--generated-at:Pin the manifest instant'
                    '--lint:Lint the packaged result the way a consumer sees it'
                    '--out:Where the distribution is written'
                    '-o:Where the distribution is written'
                    '--verify:Re-hash a finished distribution instead of packaging'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            _files
            ;;
        (site)
            case "$prev" in
                (--format) compadd -- json text; return ;;
                (--name) return ;;
                (--out|-o) _files; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--format:Output format'
                    '--json:Emit the stable JSON form instead of text'
                    '--name:The display name for the site'
                    '--out:The output directory'
                    '-o:The output directory'
                    '--single-file:Emit the whole site as one index.html'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            _files
            ;;
        (skills)
            case "$prev" in
                (--dir) _files; return ;;
                (--host) compadd -- all claude generic pi; return ;;
                (--scope) compadd -- project user; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--dir:Write into this directory as well'
                    '--force:Overwrite a file whose bytes differ'
                    '--host:Where to write'
                    '--names:List names only, one per line'
                    '--no-agents-md:Skip writing the AGENTS.md/CLAUDE.md pointer'
                    '--scope:Install for this user or beside this project'
                )
                _describe -t options 'option' options
                return
            fi
            if [[ -z "$sub" ]]; then
                compadd -- install list path
                return
            fi
            if [[ "$sub" = "path" ]]; then
                __okf_skill_names
            fi
            ;;
        (mcp)
            case "$prev" in
                (--scope) compadd -- project personal registered all; return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--scope:Which bundles the server serves'
                    '--verbose:Report vault resolution and effective configuration'
                    '-v:Report vault resolution and effective configuration'
                )
                _describe -t options 'option' options
                return
            fi
            _files
            ;;
        (upgrade)
            case "$prev" in
                (--channel) compadd -- rc stable; return ;;
                (--format) compadd -- json text; return ;;
                (--version) return ;;
            esac
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                    '--channel:The release channel to follow'
                    '--check:Report whether an upgrade is available and stop'
                    '--dry-run:Resolve and report without downloading anything'
                    '--format:Output format'
                    '--json:Emit the stable JSON form instead of text'
                    '--version:Install this release instead of the newest'
                )
                _describe -t options 'option' options
                return
            fi
            ;;
        (completion)
            if [[ "$cur" == -* ]]; then
                options=(
                    '--help:Show this help'
                    '-h:Show this help'
                )
                _describe -t options 'option' options
                return
            fi
            compadd -- bash fish pwsh zsh
            ;;
        (help)
            ;;
        (version)
            if [[ "$cur" == -* ]]; then
                options=(
                    '--verbose:Also print the commit this binary was built from'
                    '-v:Also print the commit this binary was built from'
                )
                _describe -t options 'option' options
                return
            fi
            ;;
    esac
}

# Both entry points: sourced (`eval "$(okf completion zsh)"`) the function has to
# register itself, autoloaded from $fpath it is already the completer being called.
if [ "${funcstack[1]}" = "_okf" ]; then
    _okf "$@"
else
    compdef _okf okf
fi
