# okf completion for bash. Generated by `okf completion bash`; do not edit.
#
# Load it into this shell:  eval "$(okf completion bash)"
# Install it permanently:   okf completion bash > \
#     "${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions/okf"

__okf_words() {
    COMPREPLY=( $(compgen -W "$1" -- "$2") )
}

__okf_files() {
    # A path may contain spaces, and the default IFS would split one such name
    # into several candidates. `local IFS` keeps this to the one function and
    # stays inside bash 3.2, which is what macOS still ships.
    local IFS=$'\n'
    COMPREPLY=( $(compgen -f -- "$1") )
    compopt -o filenames 2>/dev/null
}

# The only thing a completion asks okf for. It answers from the binary itself, so
# there is no vault to find and no directory to walk.
__okf_skills() {
    COMPREPLY=( $(compgen -W "$("$2" skills list --names 2>/dev/null)" -- "$1") )
}

_okf() {
    local cur prev verb sub word skip index

    # bash does not clear this between completions; a function that leaves it
    # alone offers the previous word's answers.
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev=""
    if [ "$COMP_CWORD" -gt 0 ]; then
        prev="${COMP_WORDS[COMP_CWORD-1]}"
    fi

    # The verb and its subcommand are the first two bare words that are not some
    # flag's value, which is why the value-taking flags are listed here.
    verb=""
    sub=""
    skip=0
    index=1
    while [ "$index" -lt "$COMP_CWORD" ]; do
        word="${COMP_WORDS[index]}"
        index=$((index + 1))
        if [ "$skip" = 1 ]; then
            skip=0
            continue
        fi
        case "$word" in
            --*=*) ;;
            --at|--bundle|--by|--captured-at|--channel|--concept|--config|--dir|--form|--format|--generated-at|--host|--limit|--name|--out|--scope|--severity|--source-last-modified|--tag|--title|--type|--url|--verify|--version|-o) skip=1 ;;
            -*) ;;
            *)
                if [ -z "$verb" ]; then
                    verb="$word"
                elif [ -z "$sub" ]; then
                    sub="$word"
                fi
                ;;
        esac
    done

    if [ -z "$verb" ]; then
        __okf_words "init lint index search register unregister registry inbox candidates verify capture generated bundle site skills mcp upgrade completion help version --help -h --version" "$cur"
        return
    fi

    case "$verb" in
        init)
            case "$prev" in
                --name) return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --name --no-agents-md --personal --verbose -v" "$cur"; return ;;
            esac
            __okf_files "$cur"
            ;;
        lint)
            case "$prev" in
                --config) __okf_files "$cur"; return ;;
                --format) __okf_words "json text" "$cur"; return ;;
                --severity) __okf_words "OKF0001 OKF0002 OKF0003 OKF0004 OKF0101 OKF0102 OKF0103 OKF0201 OKF0202 OKF0301 OKF0302 OKF0303 OKF0304 OKF0305 OKF0306 OKF0307 OKF0308 OKF0309 OKF0310" "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --config --format --json --list-rules --severity --treat-all-warnings-as-errors --verbose -v" "$cur"; return ;;
            esac
            __okf_files "$cur"
            ;;
        index)
            case "$prev" in
                --format) __okf_words "json text" "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --check --format --json --verbose -v" "$cur"; return ;;
            esac
            __okf_files "$cur"
            ;;
        search)
            case "$prev" in
                --format) __okf_words "json text" "$cur"; return ;;
                --limit|--tag|--type) return ;;
                --scope) __okf_words "project personal registered all" "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --format --json --limit --scope --tag --type --verbose -v" "$cur"; return ;;
            esac
            ;;
        register)
            case "$prev" in
                --format) __okf_words "json text" "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --format --json --verbose -v" "$cur"; return ;;
            esac
            __okf_files "$cur"
            ;;
        unregister)
            case "$prev" in
                --format) __okf_words "json text" "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --format --json --verbose -v" "$cur"; return ;;
            esac
            __okf_files "$cur"
            ;;
        registry)
            case "$prev" in
                --format) __okf_words "json text" "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --format --json --verbose -v" "$cur"; return ;;
            esac
            if [ -z "$sub" ]; then
                __okf_words "list prune" "$cur"
                return
            fi
            ;;
        inbox)
            case "$prev" in
                --format) __okf_words "json text" "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --fail-if-any --format --json --verbose -v" "$cur"; return ;;
            esac
            __okf_files "$cur"
            ;;
        candidates)
            case "$prev" in
                --format) __okf_words "json text" "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --format --json --verbose -v" "$cur"; return ;;
            esac
            __okf_files "$cur"
            ;;
        verify)
            case "$prev" in
                --by) return ;;
                --config) __okf_files "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --by --config --dry-run --verbose -v" "$cur"; return ;;
            esac
            __okf_files "$cur"
            ;;
        capture)
            case "$prev" in
                --at|--by|--captured-at|--source-last-modified|--title|--url) return ;;
                --concept) __okf_files "$cur"; return ;;
                --form) __okf_words "flat packet" "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --at --by --captured-at --concept --form --json --source-last-modified --title --url" "$cur"; return ;;
            esac
            if [ -z "$sub" ]; then
                __okf_words "add close" "$cur"
                return
            fi
            __okf_files "$cur"
            ;;
        generated)
            case "$prev" in
                --at|--by) return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --at --by --dry-run" "$cur"; return ;;
            esac
            if [ -z "$sub" ]; then
                __okf_words "stamp" "$cur"
                return
            fi
            __okf_files "$cur"
            ;;
        bundle)
            case "$prev" in
                --bundle|--generated-at) return ;;
                --format) __okf_words "dir tar.gz zip" "$cur"; return ;;
                --out|-o|--verify) __okf_files "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --bundle --format --generated-at --lint --out -o --verify --verbose -v" "$cur"; return ;;
            esac
            __okf_files "$cur"
            ;;
        site)
            case "$prev" in
                --format) __okf_words "json text" "$cur"; return ;;
                --name) return ;;
                --out|-o) __okf_files "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --format --json --name --out -o --single-file --verbose -v" "$cur"; return ;;
            esac
            __okf_files "$cur"
            ;;
        skills)
            case "$prev" in
                --dir) __okf_files "$cur"; return ;;
                --host) __okf_words "all claude generic pi" "$cur"; return ;;
                --scope) __okf_words "project user" "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --dir --force --host --names --no-agents-md --scope" "$cur"; return ;;
            esac
            if [ -z "$sub" ]; then
                __okf_words "install list path" "$cur"
                return
            fi
            if [ "$sub" = "path" ]; then
                __okf_skills "$cur" "${COMP_WORDS[0]}"
            fi
            ;;
        mcp)
            case "$prev" in
                --scope) __okf_words "project personal registered all" "$cur"; return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --scope --verbose -v" "$cur"; return ;;
            esac
            __okf_files "$cur"
            ;;
        upgrade)
            case "$prev" in
                --channel) __okf_words "rc stable" "$cur"; return ;;
                --format) __okf_words "json text" "$cur"; return ;;
                --version) return ;;
            esac
            case "$cur" in
                -*) __okf_words "--help -h --channel --check --dry-run --format --json --version" "$cur"; return ;;
            esac
            ;;
        completion)
            case "$cur" in
                -*) __okf_words "--help -h" "$cur"; return ;;
            esac
            __okf_words "bash fish pwsh zsh" "$cur"
            ;;
        help)
            ;;
        version)
            case "$cur" in
                -*) __okf_words "--verbose -v" "$cur"; return ;;
            esac
            ;;
    esac
}

complete -F _okf okf
