# okf completion for fish. Generated by `okf completion fish`; do not edit.
#
# Load it into this shell:  okf completion fish | source
# Install it permanently:   okf completion fish > \
#     "$XDG_CONFIG_HOME/fish/completions/okf.fish"  (else ~/.config/fish/completions)

# The verb position: no files here, only verbs.
complete -c okf -n '__fish_use_subcommand' -f -a 'init' -d 'Scaffold a vault'
complete -c okf -n '__fish_use_subcommand' -f -a 'lint' -d 'Validate conformance plus the configured warning set'
complete -c okf -n '__fish_use_subcommand' -f -a 'index' -d 'Generate the index.md files for a bundle'
complete -c okf -n '__fish_use_subcommand' -f -a 'search' -d 'Search the resolved bundles'
complete -c okf -n '__fish_use_subcommand' -f -a 'register' -d 'Add a vault or bundle to the registry'
complete -c okf -n '__fish_use_subcommand' -f -a 'unregister' -d 'Remove a registry entry'
complete -c okf -n '__fish_use_subcommand' -f -a 'registry' -d 'Report the registry or drop entries whose path is gone'
complete -c okf -n '__fish_use_subcommand' -f -a 'inbox' -d 'List the concepts waiting on a person'
complete -c okf -n '__fish_use_subcommand' -f -a 'verify' -d 'Stamp human verification on one or more concepts'
complete -c okf -n '__fish_use_subcommand' -f -a 'capture' -d 'Record a raw/ capture or close its ingestion'
complete -c okf -n '__fish_use_subcommand' -f -a 'generated' -d 'Write the generated stamp a producer owes'
complete -c okf -n '__fish_use_subcommand' -f -a 'bundle' -d 'Package the bundles for consume-only distribution'
complete -c okf -n '__fish_use_subcommand' -f -a 'site' -d 'Render the bundles as a static site'
complete -c okf -n '__fish_use_subcommand' -f -a 'skills' -d 'The agent skills this binary carries and where they install'
complete -c okf -n '__fish_use_subcommand' -f -a 'mcp' -d 'Run the read-only MCP server over stdio'
complete -c okf -n '__fish_use_subcommand' -f -a 'upgrade' -d 'Replace this binary with the newest release'
complete -c okf -n '__fish_use_subcommand' -f -a 'completion' -d 'Print a shell completion script'
complete -c okf -n '__fish_use_subcommand' -f -a 'help' -d 'Show the verb list'
complete -c okf -n '__fish_use_subcommand' -f -a 'version' -d 'Show the version'

# okf init
complete -c okf -n '__fish_seen_subcommand_from init' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from init' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from init' -l name -x -d 'The bundle directory to create'
complete -c okf -n '__fish_seen_subcommand_from init' -l personal -d 'Scaffold the personal vault rather than a project one'
complete -c okf -n '__fish_seen_subcommand_from init' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from init' -s v -d 'Report vault resolution and effective configuration'

# okf lint
complete -c okf -n '__fish_seen_subcommand_from lint' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from lint' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from lint' -l config -r -F -d 'Read this project config instead of the vault config'
complete -c okf -n '__fish_seen_subcommand_from lint' -l format -x -a 'json text' -d 'Output format'
complete -c okf -n '__fish_seen_subcommand_from lint' -l json -d 'Emit the stable JSON form instead of text'
complete -c okf -n '__fish_seen_subcommand_from lint' -l list-rules -d 'Print the rule catalog and stop'
complete -c okf -n '__fish_seen_subcommand_from lint' -l severity -x -a 'OKF0001 OKF0002 OKF0003 OKF0004 OKF0101 OKF0102 OKF0103 OKF0201 OKF0202 OKF0301 OKF0302 OKF0303 OKF0304 OKF0305 OKF0306 OKF0307 OKF0308 OKF0309 OKF0310' -d 'Override the severity of one rule as OKF####=level'
complete -c okf -n '__fish_seen_subcommand_from lint' -l treat-all-warnings-as-errors -d 'Promote every warning to an error'
complete -c okf -n '__fish_seen_subcommand_from lint' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from lint' -s v -d 'Report vault resolution and effective configuration'

# okf index
complete -c okf -n '__fish_seen_subcommand_from index' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from index' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from index' -l check -d 'Write nothing and fail on drift'
complete -c okf -n '__fish_seen_subcommand_from index' -l format -x -a 'json text' -d 'Output format'
complete -c okf -n '__fish_seen_subcommand_from index' -l json -d 'Emit the stable JSON form instead of text'
complete -c okf -n '__fish_seen_subcommand_from index' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from index' -s v -d 'Report vault resolution and effective configuration'

# okf search
complete -c okf -n '__fish_seen_subcommand_from search' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from search' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from search' -l format -x -a 'json text' -d 'Output format'
complete -c okf -n '__fish_seen_subcommand_from search' -l json -d 'Emit the stable JSON form instead of text'
complete -c okf -n '__fish_seen_subcommand_from search' -l limit -x -d 'How many results to report at most'
complete -c okf -n '__fish_seen_subcommand_from search' -l scope -x -a 'project personal registered all' -d 'Which bundles the search covers'
complete -c okf -n '__fish_seen_subcommand_from search' -l tag -x -d 'Only concepts carrying this tag'
complete -c okf -n '__fish_seen_subcommand_from search' -l type -x -d 'Only concepts of this type'
complete -c okf -n '__fish_seen_subcommand_from search' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from search' -s v -d 'Report vault resolution and effective configuration'

# okf register
complete -c okf -n '__fish_seen_subcommand_from register' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from register' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from register' -l format -x -a 'json text' -d 'Output format'
complete -c okf -n '__fish_seen_subcommand_from register' -l json -d 'Emit the stable JSON form instead of text'
complete -c okf -n '__fish_seen_subcommand_from register' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from register' -s v -d 'Report vault resolution and effective configuration'

# okf unregister
complete -c okf -n '__fish_seen_subcommand_from unregister' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from unregister' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from unregister' -l format -x -a 'json text' -d 'Output format'
complete -c okf -n '__fish_seen_subcommand_from unregister' -l json -d 'Emit the stable JSON form instead of text'
complete -c okf -n '__fish_seen_subcommand_from unregister' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from unregister' -s v -d 'Report vault resolution and effective configuration'

# okf registry
complete -c okf -n '__fish_seen_subcommand_from registry' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from registry' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from registry' -l format -x -a 'json text' -d 'Output format'
complete -c okf -n '__fish_seen_subcommand_from registry' -l json -d 'Emit the stable JSON form instead of text'
complete -c okf -n '__fish_seen_subcommand_from registry' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from registry' -s v -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from registry; and not __fish_seen_subcommand_from list prune' -f -a 'list prune'

# okf inbox
complete -c okf -n '__fish_seen_subcommand_from inbox' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from inbox' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from inbox' -l fail-if-any -d 'Exit 1 when the inbox is not empty'
complete -c okf -n '__fish_seen_subcommand_from inbox' -l format -x -a 'json text' -d 'Output format'
complete -c okf -n '__fish_seen_subcommand_from inbox' -l json -d 'Emit the stable JSON form instead of text'
complete -c okf -n '__fish_seen_subcommand_from inbox' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from inbox' -s v -d 'Report vault resolution and effective configuration'

# okf verify
complete -c okf -n '__fish_seen_subcommand_from verify' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from verify' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from verify' -l by -x -d 'Stamp this actor instead of the resolved identity'
complete -c okf -n '__fish_seen_subcommand_from verify' -l config -r -F -d 'Read verify.actor from this project config'
complete -c okf -n '__fish_seen_subcommand_from verify' -l dry-run -d 'Report what would be written and write nothing'
complete -c okf -n '__fish_seen_subcommand_from verify' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from verify' -s v -d 'Report vault resolution and effective configuration'

# okf capture
complete -c okf -n '__fish_seen_subcommand_from capture' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from capture' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from capture' -l at -x -d 'Alias of --captured-at'
complete -c okf -n '__fish_seen_subcommand_from capture' -l by -x -d 'The capturing or ingesting actor'
complete -c okf -n '__fish_seen_subcommand_from capture' -l captured-at -x -d 'Pin the capture instant'
complete -c okf -n '__fish_seen_subcommand_from capture' -l concept -r -F -d 'A concept the ingestion produced'
complete -c okf -n '__fish_seen_subcommand_from capture' -l form -x -a 'flat packet' -d 'The shape the item takes on disk'
complete -c okf -n '__fish_seen_subcommand_from capture' -l json -d 'Emit the stable JSON form instead of text'
complete -c okf -n '__fish_seen_subcommand_from capture' -l source-last-modified -x -d 'The last-modified date the artifact itself carries'
complete -c okf -n '__fish_seen_subcommand_from capture' -l title -x -d 'The title of the captured artifact'
complete -c okf -n '__fish_seen_subcommand_from capture' -l url -x -d 'The URL the artifact came from'
complete -c okf -n '__fish_seen_subcommand_from capture; and not __fish_seen_subcommand_from add close' -f -a 'add close'

# okf generated
complete -c okf -n '__fish_seen_subcommand_from generated' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from generated' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from generated' -l at -x -d 'Pin the stamp instant'
complete -c okf -n '__fish_seen_subcommand_from generated' -l by -x -d 'The generating actor'
complete -c okf -n '__fish_seen_subcommand_from generated' -l dry-run -d 'Report what would be written and write nothing'
complete -c okf -n '__fish_seen_subcommand_from generated; and not __fish_seen_subcommand_from stamp' -f -a 'stamp'

# okf bundle
complete -c okf -n '__fish_seen_subcommand_from bundle' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from bundle' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from bundle' -l bundle -x -d 'Package only this bundle'
complete -c okf -n '__fish_seen_subcommand_from bundle' -l format -x -a 'dir tar.gz zip' -d 'The distribution shape to write'
complete -c okf -n '__fish_seen_subcommand_from bundle' -l generated-at -x -d 'Pin the manifest instant'
complete -c okf -n '__fish_seen_subcommand_from bundle' -l lint -d 'Lint the packaged result the way a consumer sees it'
complete -c okf -n '__fish_seen_subcommand_from bundle' -l out -r -F -d 'Where the distribution is written'
complete -c okf -n '__fish_seen_subcommand_from bundle' -s o -r -F -d 'Where the distribution is written'
complete -c okf -n '__fish_seen_subcommand_from bundle' -l verify -r -F -d 'Re-hash a finished distribution instead of packaging'
complete -c okf -n '__fish_seen_subcommand_from bundle' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from bundle' -s v -d 'Report vault resolution and effective configuration'

# okf site
complete -c okf -n '__fish_seen_subcommand_from site' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from site' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from site' -l format -x -a 'json text' -d 'Output format'
complete -c okf -n '__fish_seen_subcommand_from site' -l json -d 'Emit the stable JSON form instead of text'
complete -c okf -n '__fish_seen_subcommand_from site' -l name -x -d 'The display name for the site'
complete -c okf -n '__fish_seen_subcommand_from site' -l out -r -F -d 'The output directory'
complete -c okf -n '__fish_seen_subcommand_from site' -s o -r -F -d 'The output directory'
complete -c okf -n '__fish_seen_subcommand_from site' -l single-file -d 'Emit the whole site as one index.html'
complete -c okf -n '__fish_seen_subcommand_from site' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from site' -s v -d 'Report vault resolution and effective configuration'

# okf skills
complete -c okf -n '__fish_seen_subcommand_from skills' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from skills' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from skills' -l dir -r -F -d 'Write into this directory as well'
complete -c okf -n '__fish_seen_subcommand_from skills' -l force -d 'Overwrite a file whose bytes differ'
complete -c okf -n '__fish_seen_subcommand_from skills' -l host -x -a 'all claude generic pi' -d 'Where to write'
complete -c okf -n '__fish_seen_subcommand_from skills' -l names -d 'List names only, one per line'
complete -c okf -n '__fish_seen_subcommand_from skills' -l scope -x -a 'project user' -d 'Install for this user or beside this project'
complete -c okf -n '__fish_seen_subcommand_from skills; and not __fish_seen_subcommand_from install list path' -f -a 'install list path'
complete -c okf -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from path' -f -a '(okf skills list --names 2>/dev/null)'

# okf mcp
complete -c okf -n '__fish_seen_subcommand_from mcp' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from mcp' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from mcp' -l scope -x -a 'project personal registered all' -d 'Which bundles the server serves'
complete -c okf -n '__fish_seen_subcommand_from mcp' -l verbose -d 'Report vault resolution and effective configuration'
complete -c okf -n '__fish_seen_subcommand_from mcp' -s v -d 'Report vault resolution and effective configuration'

# okf upgrade
complete -c okf -n '__fish_seen_subcommand_from upgrade' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from upgrade' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from upgrade' -l channel -x -a 'rc stable' -d 'The release channel to follow'
complete -c okf -n '__fish_seen_subcommand_from upgrade' -l check -d 'Report whether an upgrade is available and stop'
complete -c okf -n '__fish_seen_subcommand_from upgrade' -l dry-run -d 'Resolve and report without downloading anything'
complete -c okf -n '__fish_seen_subcommand_from upgrade' -l format -x -a 'json text' -d 'Output format'
complete -c okf -n '__fish_seen_subcommand_from upgrade' -l json -d 'Emit the stable JSON form instead of text'
complete -c okf -n '__fish_seen_subcommand_from upgrade' -l version -x -d 'Install this release instead of the newest'
complete -c okf -n '__fish_seen_subcommand_from upgrade' -f

# okf completion
complete -c okf -n '__fish_seen_subcommand_from completion' -l help -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from completion' -s h -d 'Show this help'
complete -c okf -n '__fish_seen_subcommand_from completion' -f -a 'bash fish pwsh zsh'

# okf help
complete -c okf -n '__fish_seen_subcommand_from help' -f

# okf version
complete -c okf -n '__fish_seen_subcommand_from version' -l verbose -d 'Also print the commit this binary was built from'
complete -c okf -n '__fish_seen_subcommand_from version' -s v -d 'Also print the commit this binary was built from'
complete -c okf -n '__fish_seen_subcommand_from version' -f
