using System.Text.Json;

namespace Okf.Cli.Tests.Index;

/// <summary>
/// End-to-end <c>okf index</c> behavior: the flags, the exit-code contract (PRD CLI-10,
/// CLI-14), and regeneration over a real fixture tree.
/// </summary>
public class IndexCommandTests
{
    [Fact]
    public void HelpExitsZeroAndDescribesTheFlags()
    {
        using var home = new TempTree();
        var run = CliHarness.RunIn(home.Root, home.Root, "index", "--help");

        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);
        Assert.Contains("okf index [path] [options]", run.Output, StringComparison.Ordinal);
        Assert.Contains("--check", run.Output, StringComparison.Ordinal);
    }

    [Fact]
    public void TheCommandIsReachableFromTheTopLevelUsage()
    {
        using var home = new TempTree();
        var run = CliHarness.RunIn(home.Root, home.Root, "help");

        Assert.Contains("okf index [path]", run.Output, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("--nope")]
    [InlineData("--format=yaml")]
    public void AMalformedCommandLineIsAUsageFailure(string argument)
    {
        using var home = new TempTree();
        var run = CliHarness.RunIn(home.Root, home.Root, "index", argument);

        Assert.Equal(CliApplication.ExitUsage, run.ExitCode);
        Assert.Contains("okf: error:", run.Error, StringComparison.Ordinal);
        Assert.Empty(run.Output);
    }

    [Fact]
    public void ASecondPathIsAUsageFailure()
    {
        using var home = new TempTree();
        var run = CliHarness.RunIn(home.Root, home.Root, "index", "one", "two");

        Assert.Equal(CliApplication.ExitUsage, run.ExitCode);
        Assert.Contains("at most one path", run.Error, StringComparison.Ordinal);
    }

    [Fact]
    public void AnUnresolvableTargetIsAnEnvironmentFailure()
    {
        using var home = new TempTree();
        var run = CliHarness.RunIn(home.Root, home.Root, "index", Path.Combine(home.Root, "nowhere"));

        Assert.Equal(CliApplication.ExitUsage, run.ExitCode);
        Assert.Contains("No such directory", run.Error, StringComparison.Ordinal);
    }

    [Fact]
    public void CheckLeavesAHandWrittenBundleAloneAndExitsZero()
    {
        using var tree = new TempTree();
        var bundle = tree.CopyFixture("conformant", "bundle");
        var before = Snapshot(bundle);

        var run = CliHarness.RunIn(tree.Root, tree.Root, "index", "--check", bundle);

        // PRD ACC-1: the fixture's indexes are hand-written, exactly like Google's
        // reference bundles. Nothing okf-net did not write can drift.
        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);
        Assert.Equal("Checked 2 indexes in 1 bundle: 0 drifted.", run.Summary);
        Assert.Equal(before, Snapshot(bundle));
    }

    [Fact]
    public void WritingReplacesHandWrittenIndexesAndSaysSo()
    {
        using var tree = new TempTree();
        var bundle = tree.CopyFixture("conformant", "bundle");

        var run = CliHarness.RunIn(tree.Root, tree.Root, "index", bundle);

        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);
        Assert.Contains("2 hand-written indexes replaced", run.Summary, StringComparison.Ordinal);
        Assert.Contains("bundle/index.md: replaced (was hand-written)", run.Output, StringComparison.Ordinal);

        var root = File.ReadAllText(Path.Combine(bundle, "index.md"));
        Assert.StartsWith("---\nokf_version: \"0.2\"\n---\n\n<!-- generated by okf -->\n", root, StringComparison.Ordinal);
    }

    [Fact]
    public void RegeneratingAFixtureIsIdempotentAndLeavesItConformant()
    {
        using var tree = new TempTree();
        var bundle = tree.CopyFixture("conformant", "bundle");

        Assert.Equal(CliApplication.ExitSuccess, CliHarness.RunIn(tree.Root, tree.Root, "index", bundle).ExitCode);
        var first = Snapshot(bundle);

        var second = CliHarness.RunIn(tree.Root, tree.Root, "index", bundle);

        Assert.Equal("Generated 2 indexes in 1 bundle: 0 created, 0 updated, 2 unchanged.", second.Summary);
        Assert.Equal(first, Snapshot(bundle));
        Assert.Equal(CliApplication.ExitSuccess, CliHarness.RunIn(tree.Root, tree.Root, "index", "--check", bundle).ExitCode);

        // The generated indexes satisfy the §8 structure the linter enforces (OKF0003).
        var lint = CliHarness.RunIn(tree.Root, tree.Root, "lint", bundle);
        Assert.Equal(CliApplication.ExitSuccess, lint.ExitCode);
        Assert.DoesNotContain(": error OKF", lint.Output, StringComparison.Ordinal);
    }

    [Fact]
    public void CheckExitsOneOnceAGeneratedIndexNoLongerMatchesTheTree()
    {
        using var tree = new TempTree();
        var bundle = tree.CopyFixture("conformant", "bundle");
        CliHarness.RunIn(tree.Root, tree.Root, "index", bundle);

        File.WriteAllText(
            Path.Combine(bundle, "topics", "gadgets.md"),
            "---\ntype: Reference\ntitle: Gadgets\ndescription: A second topic.\ntags: [fixture]\n---\n\n# Gadgets\n");

        var run = CliHarness.RunIn(tree.Root, tree.Root, "index", "--check", bundle);

        Assert.Equal(CliApplication.ExitDiagnostics, run.ExitCode);
        Assert.Contains("bundle/topics/index.md: out of date", run.Output, StringComparison.Ordinal);
        Assert.Contains("Checked 2 indexes in 1 bundle: 1 drifted.", run.Output, StringComparison.Ordinal);
        Assert.Contains("Run `okf index` to regenerate.", run.Output, StringComparison.Ordinal);

        // And `okf lint` says the same thing through the rule (PRD CLI-9).
        Assert.Contains("OKF0306", CliHarness.RunIn(tree.Root, tree.Root, "lint", bundle).RuleIds);
    }

    [Fact]
    public void CheckDoesNotOfferRegenerationWhenTheOnlyDriftIsAnOrphan()
    {
        using var tree = new TempTree();
        var bundle = tree.CopyFixture("conformant", "bundle");
        CliHarness.RunIn(tree.Root, tree.Root, "index", bundle);

        // A generated index left behind in a directory whose concepts are gone.
        Directory.CreateDirectory(Path.Combine(bundle, "gone"));
        File.WriteAllText(
            Path.Combine(bundle, "gone", "index.md"),
            "<!-- generated by okf -->\n\n# Reference\n\n* [Old](old.md)\n");

        var run = CliHarness.RunIn(tree.Root, tree.Root, "index", "--check", bundle);

        Assert.Equal(CliApplication.ExitDiagnostics, run.ExitCode);
        Assert.Contains("bundle/gone/index.md: orphaned", run.Output, StringComparison.Ordinal);
        Assert.DoesNotContain(": out of date", run.Output, StringComparison.Ordinal);

        // An orphan is drift a regeneration cannot fix — the file has to go — so the hint
        // is offered only when running `okf index` would actually repair something.
        Assert.DoesNotContain("Run `okf index` to regenerate.", run.Output, StringComparison.Ordinal);
    }

    [Fact]
    public void CheckWritesNothingEvenWhenEverythingHasDrifted()
    {
        using var tree = new TempTree();
        var bundle = tree.CopyFixture("conformant", "bundle");
        CliHarness.RunIn(tree.Root, tree.Root, "index", bundle);
        File.WriteAllText(Path.Combine(bundle, "index.md"), "<!-- generated by okf -->\n\n# Nothing\n");
        var before = Snapshot(bundle);

        Assert.Equal(
            CliApplication.ExitDiagnostics,
            CliHarness.RunIn(tree.Root, tree.Root, "index", "--check", bundle).ExitCode);
        Assert.Equal(before, Snapshot(bundle));
    }

    [Fact]
    public void JsonReportsEveryIndexAndItsStatus()
    {
        using var tree = new TempTree();
        var bundle = tree.CopyFixture("conformant", "bundle");
        CliHarness.RunIn(tree.Root, tree.Root, "index", bundle);

        var run = CliHarness.RunIn(tree.Root, tree.Root, "index", "--check", "--json", bundle);

        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);
        using var document = JsonDocument.Parse(run.Output);
        var entries = document.RootElement.EnumerateArray().ToList();

        Assert.Equal(2, entries.Count);
        Assert.All(entries, entry =>
        {
            Assert.Equal("unchanged", entry.GetProperty("status").GetString());
            Assert.False(entry.GetProperty("drift").GetBoolean());
        });
        Assert.Contains(entries, entry => entry.GetProperty("bundleRoot").GetBoolean());
        Assert.Equal("bundle/index.md", entries[0].GetProperty("path").GetString());
    }

    [Fact]
    public void ItResolvesAVaultTheSameWayLintDoes()
    {
        using var tree = new TempTree();
        tree.CopyFixture("conformant", "project/okf/bundles/first");
        tree.CopyFixture("warnings-only", "project/okf/bundles/second");
        var project = Path.Combine(tree.Root, "project");

        var run = CliHarness.RunIn(project, tree.Root, "index", "--verbose");

        Assert.Equal(CliApplication.ExitSuccess, run.ExitCode);
        Assert.Contains("in 2 bundles", run.Summary, StringComparison.Ordinal);
        Assert.Contains("okf: resolved vault", run.Error, StringComparison.Ordinal);
        Assert.Contains("okf: writing generated index.md files", run.Error, StringComparison.Ordinal);
    }

    private static string Snapshot(string bundle) =>
        string.Join(
            "\n\0\n",
            Directory.EnumerateFiles(bundle, "*", SearchOption.AllDirectories)
                .OrderBy(path => path, StringComparer.Ordinal)
                .Select(path => path + "\n" + File.ReadAllText(path)));
}
